FROM golang:1.14.2 as builder

WORKDIR /go/src/github.com/fluid-cloudnative/fluid
COPY . .

RUN make databackup-build && \
    cp bin/databackup /go/bin/databackup

FROM registry.cn-huhehaote.aliyuncs.com/alluxio/alluxio:2.3.0-SNAPSHOT-985b84c
COPY --from=builder /go/bin/databackup /usr/local/bin/databackup

USER root

CMD ["databackup", "start"]