{
 "title": "Fluid-Prometheus-Grafana-Monitor",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "alluxio_datasource",
    "label": "The datasource of alluxio prometheus",
    "query": "prometheus"
   },
   { "name": "masters", "query": "master" },
   {
    "name": "workers",
    "label": "The prometheus job_name including worker nodes",
    "query": "alluxio worker"
   },
   {
    "name": "alluxio_user",
    "label": "User of runtime",
    "query": "metrics(Master_getConfiguration_User)"
   },
   { "name": "instance", "query": "label_values(instance)" },
   { "name": "fluid_runtime", "query": "label_values(fluid_runtime)" },
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Alluxio IO Key Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes Read Local (Per Minute)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "increase(Cluster_BytesReadLocal{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}[1m])",
       "legendFormat": "Bytes Read Local (Per Minute)"
      }
     ]
    },
    {
     "title": "Bytes Read Remote (Per Minute)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "increase(Cluster_BytesReadAlluxio{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}[1m])",
       "legendFormat": "Bytes Read Remote (Per Minute)"
      }
     ]
    },
    {
     "title": "Bytes Read UFS (Per Minute)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "increase(Cluster_BytesReadUfsAll{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}[1m])",
       "legendFormat": "Bytes Read UFS (Per Minute)"
      }
     ]
    },
    {
     "title": "Live Workers",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(Cluster_Workers{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Alluxio Space Used",
     "type": "graph",
     "description": "Displays the percentage of free Alluxio storage with thresholds from 100-50%, 50-10%, and 10-0%",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(Cluster_CapacityUsed{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}) / Cluster_CapacityTotal{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "% UFS Space Used",
     "type": "graph",
     "description": "The amount of bytes read from the UFSes",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "Cluster_RootUfsCapacityUsed{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}/Cluster_RootUfsCapacityTotal{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "UFS Space Used",
     "type": "graph",
     "description": "The amount of bytes read from the UFSes",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "Cluster_RootUfsCapacityTotal{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      },
      {
       "expr": "Cluster_RootUfsCapacityUsed{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Alluxio Space Used",
     "type": "graph",
     "description": "Displays the percentage of free Alluxio storage with thresholds from 100-50%, 50-10%, and 10-0%",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "Cluster_CapacityTotal{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      },
      {
       "expr": "Cluster_CapacityUsed{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logical Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Directories Created",
     "type": "stat",
     "description": "Displays the current number of how many directories Alluxio has created since starting",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Master_DirectoriesCreated{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "File Infos Got",
     "type": "stat",
     "description": "displays the number of times the FileInfosGot operation was called",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Master_FileInfosGot{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Total Paths",
     "type": "stat",
     "description": "Displays the total paths located in the Alluxio file system",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Master_TotalPaths{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Complete File Operations",
     "type": "stat",
     "description": "Displays how many times the CompleteFile operation has been called",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Master_CompleteFileOps{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Create Directory Oprtations",
     "type": "stat",
     "description": "Displays the amount of directories that Alluxio has created (Not the current amount of directories)",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Master_CreateDirectoryOps{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Delete Path Operations",
     "type": "stat",
     "description": "Displays how many times the deletePath operation has been called (And how many total paths have been deleted)",
     "gridPos": { "h": 13, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Master_DeletePathOps{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Files Pinned",
     "type": "stat",
     "description": "Displays the current number of pinned files in Alluxio",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Master_FilesPinned{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Mount Operations",
     "type": "stat",
     "description": "Displays how many times the mount operation has been called (including failed invocations)",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Master_MountOps{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Files Freed",
     "type": "stat",
     "description": "Displays the current number of freed files in Alluxio",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Master_FilesFreed{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Unmount Operations",
     "type": "stat",
     "description": "Displays how many times the unmount operation has been called",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "Master_UnmountOps{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alluxio Metadata Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "GetStatus Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "{__name__=\"Master_GetStatus_User:$alluxio_user\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.5\"}"
      },
      {
       "expr": "{__name__=\"Master_GetStatus_User:$alluxio_user\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.95\"}"
      },
      {
       "expr": "{__name__=\"Master_GetStatus_User:$alluxio_user\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.99\"}"
      }
     ]
    },
    {
     "title": "ListStatus Operation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "{__name__=\"Master_ListStatus_User:$alluxio_user\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.5\"}"
      },
      {
       "expr": "{__name__=\"Master_ListStatus_User:$alluxio_user\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.95\"}"
      },
      {
       "expr": "{__name__=\"Master_ListStatus_User:$alluxio_user\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.99\"}"
      }
     ]
    },
    {
     "title": "Get Configuration Operation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "{__name__=\"Master_getConfiguration\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.5\"}"
      },
      {
       "expr": "{__name__=\"Master_getConfiguration\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.95\"}"
      },
      {
       "expr": "{__name__=\"Master_getConfiguration\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.99\"}"
      }
     ]
    },
    {
     "title": "Block Heartbeat Operation",
     "type": "graph",
     "description": "Displays the 50th, 95th, and 99th percentiles call time for the blockHeartbeat metadata operation.\n\nNote: This is not a graph for the actual Block Heartbeat just how long it took the operation to run",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "{__name__=\"Master_blockHeartbeat_User:$alluxio_user\",fluid_runtime=~\"$fluid_runtime\",quantile=\"0.5\"}"
      },
      {
       "expr": "{__name__=\"Master_blockHeartbeat_User:$alluxio_user\",fluid_runtime=~\"$fluid_runtime\",quantile=\"0.95\"}"
      },
      {
       "expr": "{__name__=\"Master_blockHeartbeat_User:$alluxio_user\",fluid_runtime=~\"$fluid_runtime\",quantile=\"0.99\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Master JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master Pools Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=\"pools_Compressed_Class_Space_used\", fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "{__name__=\"pools_Metaspace_used\", fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "{__name__=\"pools_PS_Eden_Space_used\", fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "{__name__=\"pools_PS_Survivor_Space_used\", fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Master Heap Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=\"heap_used\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "{__name__=\"heap_max\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}"
      },
      {
       "expr": "{__name__=\"non_heap_used\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Master Total Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "{__name__=\"total_max\",fluid_runtime=~\"$fluid_runtime\"}"
      },
      {
       "expr": "{__name__=\"total_used\",fluid_runtime=~\"$fluid_runtime\"}"
      }
     ]
    }
   ]
  }
 ]
}