/*
Copyright 2023 The Fluid Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/dataoperation/interface.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	v1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	dataoperation "github.com/fluid-cloudnative/fluid/pkg/dataoperation"
	runtime "github.com/fluid-cloudnative/fluid/pkg/runtime"
	gomock "github.com/golang/mock/gomock"
	types "k8s.io/apimachinery/pkg/types"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockOperationInterfaceBuilder is a mock of OperationInterfaceBuilder interface.
type MockOperationInterfaceBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockOperationInterfaceBuilderMockRecorder
}

// MockOperationInterfaceBuilderMockRecorder is the mock recorder for MockOperationInterfaceBuilder.
type MockOperationInterfaceBuilderMockRecorder struct {
	mock *MockOperationInterfaceBuilder
}

// NewMockOperationInterfaceBuilder creates a new mock instance.
func NewMockOperationInterfaceBuilder(ctrl *gomock.Controller) *MockOperationInterfaceBuilder {
	mock := &MockOperationInterfaceBuilder{ctrl: ctrl}
	mock.recorder = &MockOperationInterfaceBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationInterfaceBuilder) EXPECT() *MockOperationInterfaceBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockOperationInterfaceBuilder) Build(object client.Object) (dataoperation.OperationInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", object)
	ret0, _ := ret[0].(dataoperation.OperationInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockOperationInterfaceBuilderMockRecorder) Build(object interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockOperationInterfaceBuilder)(nil).Build), object)
}

// MockOperationInterface is a mock of OperationInterface interface.
type MockOperationInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOperationInterfaceMockRecorder
}

// MockOperationInterfaceMockRecorder is the mock recorder for MockOperationInterface.
type MockOperationInterfaceMockRecorder struct {
	mock *MockOperationInterface
}

// NewMockOperationInterface creates a new mock instance.
func NewMockOperationInterface(ctrl *gomock.Controller) *MockOperationInterface {
	mock := &MockOperationInterface{ctrl: ctrl}
	mock.recorder = &MockOperationInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationInterface) EXPECT() *MockOperationInterfaceMockRecorder {
	return m.recorder
}

// GetChartsDirectory mocks base method.
func (m *MockOperationInterface) GetChartsDirectory() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChartsDirectory")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetChartsDirectory indicates an expected call of GetChartsDirectory.
func (mr *MockOperationInterfaceMockRecorder) GetChartsDirectory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChartsDirectory", reflect.TypeOf((*MockOperationInterface)(nil).GetChartsDirectory))
}

// GetOperationObject mocks base method.
func (m *MockOperationInterface) GetOperationObject() client.Object {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationObject")
	ret0, _ := ret[0].(client.Object)
	return ret0
}

// GetOperationObject indicates an expected call of GetOperationObject.
func (mr *MockOperationInterfaceMockRecorder) GetOperationObject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationObject", reflect.TypeOf((*MockOperationInterface)(nil).GetOperationObject))
}

// GetOperationType mocks base method.
func (m *MockOperationInterface) GetOperationType() dataoperation.OperationType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationType")
	ret0, _ := ret[0].(dataoperation.OperationType)
	return ret0
}

// GetOperationType indicates an expected call of GetOperationType.
func (mr *MockOperationInterfaceMockRecorder) GetOperationType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationType", reflect.TypeOf((*MockOperationInterface)(nil).GetOperationType))
}

// GetParallelTaskNumber mocks base method.
func (m *MockOperationInterface) GetParallelTaskNumber() int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParallelTaskNumber")
	ret0, _ := ret[0].(int32)
	return ret0
}

// GetParallelTaskNumber indicates an expected call of GetParallelTaskNumber.
func (mr *MockOperationInterfaceMockRecorder) GetParallelTaskNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParallelTaskNumber", reflect.TypeOf((*MockOperationInterface)(nil).GetParallelTaskNumber))
}

// GetPossibleTargetDatasetNamespacedNames mocks base method.
func (m *MockOperationInterface) GetPossibleTargetDatasetNamespacedNames() []types.NamespacedName {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPossibleTargetDatasetNamespacedNames")
	ret0, _ := ret[0].([]types.NamespacedName)
	return ret0
}

// GetPossibleTargetDatasetNamespacedNames indicates an expected call of GetPossibleTargetDatasetNamespacedNames.
func (mr *MockOperationInterfaceMockRecorder) GetPossibleTargetDatasetNamespacedNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPossibleTargetDatasetNamespacedNames", reflect.TypeOf((*MockOperationInterface)(nil).GetPossibleTargetDatasetNamespacedNames))
}

// GetReleaseNameSpacedName mocks base method.
func (m *MockOperationInterface) GetReleaseNameSpacedName() types.NamespacedName {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReleaseNameSpacedName")
	ret0, _ := ret[0].(types.NamespacedName)
	return ret0
}

// GetReleaseNameSpacedName indicates an expected call of GetReleaseNameSpacedName.
func (mr *MockOperationInterfaceMockRecorder) GetReleaseNameSpacedName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReleaseNameSpacedName", reflect.TypeOf((*MockOperationInterface)(nil).GetReleaseNameSpacedName))
}

// GetStatusHandler mocks base method.
func (m *MockOperationInterface) GetStatusHandler() dataoperation.StatusHandler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusHandler")
	ret0, _ := ret[0].(dataoperation.StatusHandler)
	return ret0
}

// GetStatusHandler indicates an expected call of GetStatusHandler.
func (mr *MockOperationInterfaceMockRecorder) GetStatusHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusHandler", reflect.TypeOf((*MockOperationInterface)(nil).GetStatusHandler))
}

// GetTTL mocks base method.
func (m *MockOperationInterface) GetTTL() (*int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTTL")
	ret0, _ := ret[0].(*int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTTL indicates an expected call of GetTTL.
func (mr *MockOperationInterfaceMockRecorder) GetTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTTL", reflect.TypeOf((*MockOperationInterface)(nil).GetTTL))
}

// GetTargetDataset mocks base method.
func (m *MockOperationInterface) GetTargetDataset() (*v1alpha1.Dataset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetDataset")
	ret0, _ := ret[0].(*v1alpha1.Dataset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTargetDataset indicates an expected call of GetTargetDataset.
func (mr *MockOperationInterfaceMockRecorder) GetTargetDataset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetDataset", reflect.TypeOf((*MockOperationInterface)(nil).GetTargetDataset))
}

// HasPrecedingOperation mocks base method.
func (m *MockOperationInterface) HasPrecedingOperation() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPrecedingOperation")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasPrecedingOperation indicates an expected call of HasPrecedingOperation.
func (mr *MockOperationInterfaceMockRecorder) HasPrecedingOperation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPrecedingOperation", reflect.TypeOf((*MockOperationInterface)(nil).HasPrecedingOperation))
}

// RemoveTargetDatasetStatusInProgress mocks base method.
func (m *MockOperationInterface) RemoveTargetDatasetStatusInProgress(dataset *v1alpha1.Dataset) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveTargetDatasetStatusInProgress", dataset)
}

// RemoveTargetDatasetStatusInProgress indicates an expected call of RemoveTargetDatasetStatusInProgress.
func (mr *MockOperationInterfaceMockRecorder) RemoveTargetDatasetStatusInProgress(dataset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTargetDatasetStatusInProgress", reflect.TypeOf((*MockOperationInterface)(nil).RemoveTargetDatasetStatusInProgress), dataset)
}

// SetTargetDatasetStatusInProgress mocks base method.
func (m *MockOperationInterface) SetTargetDatasetStatusInProgress(dataset *v1alpha1.Dataset) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTargetDatasetStatusInProgress", dataset)
}

// SetTargetDatasetStatusInProgress indicates an expected call of SetTargetDatasetStatusInProgress.
func (mr *MockOperationInterfaceMockRecorder) SetTargetDatasetStatusInProgress(dataset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTargetDatasetStatusInProgress", reflect.TypeOf((*MockOperationInterface)(nil).SetTargetDatasetStatusInProgress), dataset)
}

// UpdateOperationApiStatus mocks base method.
func (m *MockOperationInterface) UpdateOperationApiStatus(opStatus *v1alpha1.OperationStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOperationApiStatus", opStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOperationApiStatus indicates an expected call of UpdateOperationApiStatus.
func (mr *MockOperationInterfaceMockRecorder) UpdateOperationApiStatus(opStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOperationApiStatus", reflect.TypeOf((*MockOperationInterface)(nil).UpdateOperationApiStatus), opStatus)
}

// UpdateStatusInfoForCompleted mocks base method.
func (m *MockOperationInterface) UpdateStatusInfoForCompleted(infos map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusInfoForCompleted", infos)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusInfoForCompleted indicates an expected call of UpdateStatusInfoForCompleted.
func (mr *MockOperationInterfaceMockRecorder) UpdateStatusInfoForCompleted(infos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusInfoForCompleted", reflect.TypeOf((*MockOperationInterface)(nil).UpdateStatusInfoForCompleted), infos)
}

// Validate mocks base method.
func (m *MockOperationInterface) Validate(ctx runtime.ReconcileRequestContext) ([]v1alpha1.Condition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx)
	ret0, _ := ret[0].([]v1alpha1.Condition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockOperationInterfaceMockRecorder) Validate(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockOperationInterface)(nil).Validate), ctx)
}

// MockStatusHandler is a mock of StatusHandler interface.
type MockStatusHandler struct {
	ctrl     *gomock.Controller
	recorder *MockStatusHandlerMockRecorder
}

// MockStatusHandlerMockRecorder is the mock recorder for MockStatusHandler.
type MockStatusHandlerMockRecorder struct {
	mock *MockStatusHandler
}

// NewMockStatusHandler creates a new mock instance.
func NewMockStatusHandler(ctrl *gomock.Controller) *MockStatusHandler {
	mock := &MockStatusHandler{ctrl: ctrl}
	mock.recorder = &MockStatusHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusHandler) EXPECT() *MockStatusHandlerMockRecorder {
	return m.recorder
}

// GetOperationStatus mocks base method.
func (m *MockStatusHandler) GetOperationStatus(ctx runtime.ReconcileRequestContext, opStatus *v1alpha1.OperationStatus) (*v1alpha1.OperationStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationStatus", ctx, opStatus)
	ret0, _ := ret[0].(*v1alpha1.OperationStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperationStatus indicates an expected call of GetOperationStatus.
func (mr *MockStatusHandlerMockRecorder) GetOperationStatus(ctx, opStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationStatus", reflect.TypeOf((*MockStatusHandler)(nil).GetOperationStatus), ctx, opStatus)
}
