# FROM debian:bookworm-slim
FROM debian:bookworm-slim@sha256:e5865e6858dacc255bead044a7f2d0ad8c362433cfaa5acefb670c1edf54dfef

RUN apt update && \
    apt install -y --no-install-recommends python3 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/fluid

COPY ./tools/file-prefetcher/main.py ./tools/file-prefetcher/entrypoint.sh /usr/local/fluid/

RUN chmod u+x /usr/local/fluid/entrypoint.sh

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["/usr/local/fluid/entrypoint.sh"]
