/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeJuiceFSRuntimes implements JuiceFSRuntimeInterface
type FakeJuiceFSRuntimes struct {
	Fake *FakeDataV1alpha1
	ns   string
}

var juicefsruntimesResource = schema.GroupVersionResource{Group: "data.fluid.io", Version: "v1alpha1", Resource: "juicefsruntimes"}

var juicefsruntimesKind = schema.GroupVersionKind{Group: "data.fluid.io", Version: "v1alpha1", Kind: "JuiceFSRuntime"}

// Get takes name of the juiceFSRuntime, and returns the corresponding juiceFSRuntime object, and an error if there is any.
func (c *FakeJuiceFSRuntimes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.JuiceFSRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(juicefsruntimesResource, c.ns, name), &v1alpha1.JuiceFSRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JuiceFSRuntime), err
}

// List takes label and field selectors, and returns the list of JuiceFSRuntimes that match those selectors.
func (c *FakeJuiceFSRuntimes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.JuiceFSRuntimeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(juicefsruntimesResource, juicefsruntimesKind, c.ns, opts), &v1alpha1.JuiceFSRuntimeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.JuiceFSRuntimeList{ListMeta: obj.(*v1alpha1.JuiceFSRuntimeList).ListMeta}
	for _, item := range obj.(*v1alpha1.JuiceFSRuntimeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested juiceFSRuntimes.
func (c *FakeJuiceFSRuntimes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(juicefsruntimesResource, c.ns, opts))

}

// Create takes the representation of a juiceFSRuntime and creates it.  Returns the server's representation of the juiceFSRuntime, and an error, if there is any.
func (c *FakeJuiceFSRuntimes) Create(ctx context.Context, juiceFSRuntime *v1alpha1.JuiceFSRuntime, opts v1.CreateOptions) (result *v1alpha1.JuiceFSRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(juicefsruntimesResource, c.ns, juiceFSRuntime), &v1alpha1.JuiceFSRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JuiceFSRuntime), err
}

// Update takes the representation of a juiceFSRuntime and updates it. Returns the server's representation of the juiceFSRuntime, and an error, if there is any.
func (c *FakeJuiceFSRuntimes) Update(ctx context.Context, juiceFSRuntime *v1alpha1.JuiceFSRuntime, opts v1.UpdateOptions) (result *v1alpha1.JuiceFSRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(juicefsruntimesResource, c.ns, juiceFSRuntime), &v1alpha1.JuiceFSRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JuiceFSRuntime), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeJuiceFSRuntimes) UpdateStatus(ctx context.Context, juiceFSRuntime *v1alpha1.JuiceFSRuntime, opts v1.UpdateOptions) (*v1alpha1.JuiceFSRuntime, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(juicefsruntimesResource, "status", c.ns, juiceFSRuntime), &v1alpha1.JuiceFSRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JuiceFSRuntime), err
}

// Delete takes name of the juiceFSRuntime and deletes it. Returns an error if one occurs.
func (c *FakeJuiceFSRuntimes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(juicefsruntimesResource, c.ns, name, opts), &v1alpha1.JuiceFSRuntime{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJuiceFSRuntimes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(juicefsruntimesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.JuiceFSRuntimeList{})
	return err
}

// Patch applies the patch and returns the patched juiceFSRuntime.
func (c *FakeJuiceFSRuntimes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.JuiceFSRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(juicefsruntimesResource, c.ns, name, pt, data, subresources...), &v1alpha1.JuiceFSRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JuiceFSRuntime), err
}
