/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeJindoRuntimes implements JindoRuntimeInterface
type FakeJindoRuntimes struct {
	Fake *FakeDataV1alpha1
	ns   string
}

var jindoruntimesResource = schema.GroupVersionResource{Group: "data.fluid.io", Version: "v1alpha1", Resource: "jindoruntimes"}

var jindoruntimesKind = schema.GroupVersionKind{Group: "data.fluid.io", Version: "v1alpha1", Kind: "JindoRuntime"}

// Get takes name of the jindoRuntime, and returns the corresponding jindoRuntime object, and an error if there is any.
func (c *FakeJindoRuntimes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.JindoRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(jindoruntimesResource, c.ns, name), &v1alpha1.JindoRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JindoRuntime), err
}

// List takes label and field selectors, and returns the list of JindoRuntimes that match those selectors.
func (c *FakeJindoRuntimes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.JindoRuntimeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(jindoruntimesResource, jindoruntimesKind, c.ns, opts), &v1alpha1.JindoRuntimeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.JindoRuntimeList{ListMeta: obj.(*v1alpha1.JindoRuntimeList).ListMeta}
	for _, item := range obj.(*v1alpha1.JindoRuntimeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested jindoRuntimes.
func (c *FakeJindoRuntimes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(jindoruntimesResource, c.ns, opts))

}

// Create takes the representation of a jindoRuntime and creates it.  Returns the server's representation of the jindoRuntime, and an error, if there is any.
func (c *FakeJindoRuntimes) Create(ctx context.Context, jindoRuntime *v1alpha1.JindoRuntime, opts v1.CreateOptions) (result *v1alpha1.JindoRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(jindoruntimesResource, c.ns, jindoRuntime), &v1alpha1.JindoRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JindoRuntime), err
}

// Update takes the representation of a jindoRuntime and updates it. Returns the server's representation of the jindoRuntime, and an error, if there is any.
func (c *FakeJindoRuntimes) Update(ctx context.Context, jindoRuntime *v1alpha1.JindoRuntime, opts v1.UpdateOptions) (result *v1alpha1.JindoRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(jindoruntimesResource, c.ns, jindoRuntime), &v1alpha1.JindoRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JindoRuntime), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeJindoRuntimes) UpdateStatus(ctx context.Context, jindoRuntime *v1alpha1.JindoRuntime, opts v1.UpdateOptions) (*v1alpha1.JindoRuntime, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(jindoruntimesResource, "status", c.ns, jindoRuntime), &v1alpha1.JindoRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JindoRuntime), err
}

// Delete takes name of the jindoRuntime and deletes it. Returns an error if one occurs.
func (c *FakeJindoRuntimes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(jindoruntimesResource, c.ns, name, opts), &v1alpha1.JindoRuntime{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJindoRuntimes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(jindoruntimesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.JindoRuntimeList{})
	return err
}

// Patch applies the patch and returns the patched jindoRuntime.
func (c *FakeJindoRuntimes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.JindoRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jindoruntimesResource, c.ns, name, pt, data, subresources...), &v1alpha1.JindoRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JindoRuntime), err
}
