/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDataLoads implements DataLoadInterface
type FakeDataLoads struct {
	Fake *FakeDataV1alpha1
	ns   string
}

var dataloadsResource = schema.GroupVersionResource{Group: "data.fluid.io", Version: "v1alpha1", Resource: "dataloads"}

var dataloadsKind = schema.GroupVersionKind{Group: "data.fluid.io", Version: "v1alpha1", Kind: "DataLoad"}

// Get takes name of the dataLoad, and returns the corresponding dataLoad object, and an error if there is any.
func (c *FakeDataLoads) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DataLoad, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dataloadsResource, c.ns, name), &v1alpha1.DataLoad{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataLoad), err
}

// List takes label and field selectors, and returns the list of DataLoads that match those selectors.
func (c *FakeDataLoads) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DataLoadList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dataloadsResource, dataloadsKind, c.ns, opts), &v1alpha1.DataLoadList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DataLoadList{ListMeta: obj.(*v1alpha1.DataLoadList).ListMeta}
	for _, item := range obj.(*v1alpha1.DataLoadList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dataLoads.
func (c *FakeDataLoads) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dataloadsResource, c.ns, opts))

}

// Create takes the representation of a dataLoad and creates it.  Returns the server's representation of the dataLoad, and an error, if there is any.
func (c *FakeDataLoads) Create(ctx context.Context, dataLoad *v1alpha1.DataLoad, opts v1.CreateOptions) (result *v1alpha1.DataLoad, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dataloadsResource, c.ns, dataLoad), &v1alpha1.DataLoad{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataLoad), err
}

// Update takes the representation of a dataLoad and updates it. Returns the server's representation of the dataLoad, and an error, if there is any.
func (c *FakeDataLoads) Update(ctx context.Context, dataLoad *v1alpha1.DataLoad, opts v1.UpdateOptions) (result *v1alpha1.DataLoad, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dataloadsResource, c.ns, dataLoad), &v1alpha1.DataLoad{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataLoad), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDataLoads) UpdateStatus(ctx context.Context, dataLoad *v1alpha1.DataLoad, opts v1.UpdateOptions) (*v1alpha1.DataLoad, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dataloadsResource, "status", c.ns, dataLoad), &v1alpha1.DataLoad{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataLoad), err
}

// Delete takes name of the dataLoad and deletes it. Returns an error if one occurs.
func (c *FakeDataLoads) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(dataloadsResource, c.ns, name, opts), &v1alpha1.DataLoad{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDataLoads) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dataloadsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DataLoadList{})
	return err
}

// Patch applies the patch and returns the patched dataLoad.
func (c *FakeDataLoads) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DataLoad, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dataloadsResource, c.ns, name, pt, data, subresources...), &v1alpha1.DataLoad{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataLoad), err
}
