/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAlluxioRuntimes implements AlluxioRuntimeInterface
type FakeAlluxioRuntimes struct {
	Fake *FakeDataV1alpha1
	ns   string
}

var alluxioruntimesResource = schema.GroupVersionResource{Group: "data.fluid.io", Version: "v1alpha1", Resource: "alluxioruntimes"}

var alluxioruntimesKind = schema.GroupVersionKind{Group: "data.fluid.io", Version: "v1alpha1", Kind: "AlluxioRuntime"}

// Get takes name of the alluxioRuntime, and returns the corresponding alluxioRuntime object, and an error if there is any.
func (c *FakeAlluxioRuntimes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AlluxioRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(alluxioruntimesResource, c.ns, name), &v1alpha1.AlluxioRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlluxioRuntime), err
}

// List takes label and field selectors, and returns the list of AlluxioRuntimes that match those selectors.
func (c *FakeAlluxioRuntimes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AlluxioRuntimeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(alluxioruntimesResource, alluxioruntimesKind, c.ns, opts), &v1alpha1.AlluxioRuntimeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AlluxioRuntimeList{ListMeta: obj.(*v1alpha1.AlluxioRuntimeList).ListMeta}
	for _, item := range obj.(*v1alpha1.AlluxioRuntimeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested alluxioRuntimes.
func (c *FakeAlluxioRuntimes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(alluxioruntimesResource, c.ns, opts))

}

// Create takes the representation of a alluxioRuntime and creates it.  Returns the server's representation of the alluxioRuntime, and an error, if there is any.
func (c *FakeAlluxioRuntimes) Create(ctx context.Context, alluxioRuntime *v1alpha1.AlluxioRuntime, opts v1.CreateOptions) (result *v1alpha1.AlluxioRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(alluxioruntimesResource, c.ns, alluxioRuntime), &v1alpha1.AlluxioRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlluxioRuntime), err
}

// Update takes the representation of a alluxioRuntime and updates it. Returns the server's representation of the alluxioRuntime, and an error, if there is any.
func (c *FakeAlluxioRuntimes) Update(ctx context.Context, alluxioRuntime *v1alpha1.AlluxioRuntime, opts v1.UpdateOptions) (result *v1alpha1.AlluxioRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(alluxioruntimesResource, c.ns, alluxioRuntime), &v1alpha1.AlluxioRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlluxioRuntime), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAlluxioRuntimes) UpdateStatus(ctx context.Context, alluxioRuntime *v1alpha1.AlluxioRuntime, opts v1.UpdateOptions) (*v1alpha1.AlluxioRuntime, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(alluxioruntimesResource, "status", c.ns, alluxioRuntime), &v1alpha1.AlluxioRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlluxioRuntime), err
}

// Delete takes name of the alluxioRuntime and deletes it. Returns an error if one occurs.
func (c *FakeAlluxioRuntimes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(alluxioruntimesResource, c.ns, name, opts), &v1alpha1.AlluxioRuntime{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAlluxioRuntimes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(alluxioruntimesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AlluxioRuntimeList{})
	return err
}

// Patch applies the patch and returns the patched alluxioRuntime.
func (c *FakeAlluxioRuntimes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AlluxioRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(alluxioruntimesResource, c.ns, name, pt, data, subresources...), &v1alpha1.AlluxioRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlluxioRuntime), err
}
