/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEFCRuntimes implements EFCRuntimeInterface
type FakeEFCRuntimes struct {
	Fake *FakeDataV1alpha1
	ns   string
}

var efcruntimesResource = schema.GroupVersionResource{Group: "data.fluid.io", Version: "v1alpha1", Resource: "efcruntimes"}

var efcruntimesKind = schema.GroupVersionKind{Group: "data.fluid.io", Version: "v1alpha1", Kind: "EFCRuntime"}

// Get takes name of the eFCRuntime, and returns the corresponding eFCRuntime object, and an error if there is any.
func (c *FakeEFCRuntimes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.EFCRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(efcruntimesResource, c.ns, name), &v1alpha1.EFCRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EFCRuntime), err
}

// List takes label and field selectors, and returns the list of EFCRuntimes that match those selectors.
func (c *FakeEFCRuntimes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EFCRuntimeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(efcruntimesResource, efcruntimesKind, c.ns, opts), &v1alpha1.EFCRuntimeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EFCRuntimeList{ListMeta: obj.(*v1alpha1.EFCRuntimeList).ListMeta}
	for _, item := range obj.(*v1alpha1.EFCRuntimeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested eFCRuntimes.
func (c *FakeEFCRuntimes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(efcruntimesResource, c.ns, opts))

}

// Create takes the representation of a eFCRuntime and creates it.  Returns the server's representation of the eFCRuntime, and an error, if there is any.
func (c *FakeEFCRuntimes) Create(ctx context.Context, eFCRuntime *v1alpha1.EFCRuntime, opts v1.CreateOptions) (result *v1alpha1.EFCRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(efcruntimesResource, c.ns, eFCRuntime), &v1alpha1.EFCRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EFCRuntime), err
}

// Update takes the representation of a eFCRuntime and updates it. Returns the server's representation of the eFCRuntime, and an error, if there is any.
func (c *FakeEFCRuntimes) Update(ctx context.Context, eFCRuntime *v1alpha1.EFCRuntime, opts v1.UpdateOptions) (result *v1alpha1.EFCRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(efcruntimesResource, c.ns, eFCRuntime), &v1alpha1.EFCRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EFCRuntime), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEFCRuntimes) UpdateStatus(ctx context.Context, eFCRuntime *v1alpha1.EFCRuntime, opts v1.UpdateOptions) (*v1alpha1.EFCRuntime, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(efcruntimesResource, "status", c.ns, eFCRuntime), &v1alpha1.EFCRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EFCRuntime), err
}

// Delete takes name of the eFCRuntime and deletes it. Returns an error if one occurs.
func (c *FakeEFCRuntimes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(efcruntimesResource, c.ns, name, opts), &v1alpha1.EFCRuntime{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEFCRuntimes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(efcruntimesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.EFCRuntimeList{})
	return err
}

// Patch applies the patch and returns the patched eFCRuntime.
func (c *FakeEFCRuntimes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EFCRuntime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(efcruntimesResource, c.ns, name, pt, data, subresources...), &v1alpha1.EFCRuntime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EFCRuntime), err
}
