//go:build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIGatewayStatus) DeepCopyInto(out *APIGatewayStatus) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIGatewayStatus.
func (in *APIGatewayStatus) DeepCopy() *APIGatewayStatus {
	if in == nil { return nil }
	out := new(APIGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AffinityStrategy) DeepCopyInto(out *AffinityStrategy) {
*out = *in
if in.DependOn != nil {
in, out := &in.DependOn, &out.DependOn
*out = new(ObjectRef)
**out = **in
}
if in.Prefers != nil {
in, out := &in.Prefers, &out.Prefers
*out = make([]Prefer, len(*in))
copy(*out, *in)
}
if in.Requires != nil {
in, out := &in.Requires, &out.Requires
*out = make([]Require, len(*in))
copy(*out, *in)
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AffinityStrategy.
func (in *AffinityStrategy) DeepCopy() *AffinityStrategy {
	if in == nil { return nil }
	out := new(AffinityStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlluxioCompTemplateSpec) DeepCopyInto(out *AlluxioCompTemplateSpec) {
*out = *in
if in.JvmOptions != nil {
in, out := &in.JvmOptions, &out.JvmOptions
*out = make([]string, len(*in))
copy(*out, *in)
}
if in.Properties != nil {
in, out := &in.Properties, &out.Properties
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.Ports != nil {
in, out := &in.Ports, &out.Ports
*out = make(map[string]int, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlluxioCompTemplateSpec.
func (in *AlluxioCompTemplateSpec) DeepCopy() *AlluxioCompTemplateSpec {
	if in == nil { return nil }
	out := new(AlluxioCompTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlluxioFuseSpec) DeepCopyInto(out *AlluxioFuseSpec) {
*out = *in
if in.ImagePullSecrets != nil {
in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
if in.JvmOptions != nil {
in, out := &in.JvmOptions, &out.JvmOptions
*out = make([]string, len(*in))
copy(*out, *in)
}
if in.Properties != nil {
in, out := &in.Properties, &out.Properties
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.Env != nil {
in, out := &in.Env, &out.Env
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlluxioFuseSpec.
func (in *AlluxioFuseSpec) DeepCopy() *AlluxioFuseSpec {
	if in == nil { return nil }
	out := new(AlluxioFuseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlluxioRuntime) DeepCopyInto(out *AlluxioRuntime) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlluxioRuntime.
func (in *AlluxioRuntime) DeepCopy() *AlluxioRuntime {
	if in == nil { return nil }
	out := new(AlluxioRuntime)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlluxioRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlluxioRuntimeList) DeepCopyInto(out *AlluxioRuntimeList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlluxioRuntimeList.
func (in *AlluxioRuntimeList) DeepCopy() *AlluxioRuntimeList {
	if in == nil { return nil }
	out := new(AlluxioRuntimeList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlluxioRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlluxioRuntimeSpec) DeepCopyInto(out *AlluxioRuntimeSpec) {
*out = *in
out.AlluxioVersion = in.AlluxioVersion
in.Master.DeepCopyInto(&out.Master)
in.JobMaster.DeepCopyInto(&out.JobMaster)
in.Worker.DeepCopyInto(&out.Worker)
in.JobWorker.DeepCopyInto(&out.JobWorker)
in.APIGateway.DeepCopyInto(&out.APIGateway)
in.InitUsers.DeepCopyInto(&out.InitUsers)
in.Fuse.DeepCopyInto(&out.Fuse)
if in.Properties != nil {
in, out := &in.Properties, &out.Properties
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.JvmOptions != nil {
in, out := &in.JvmOptions, &out.JvmOptions
*out = make([]string, len(*in))
copy(*out, *in)
}
in.TieredStore.DeepCopyInto(&out.TieredStore)
out.Data = in.Data
if in.RunAs != nil {
in, out := &in.RunAs, &out.RunAs
*out = new(User)
(*in).DeepCopyInto(*out)
}
if in.Volumes != nil {
in, out := &in.Volumes, &out.Volumes
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
in.PodMetadata.DeepCopyInto(&out.PodMetadata)
in.RuntimeManagement.DeepCopyInto(&out.RuntimeManagement)
if in.ImagePullSecrets != nil {
in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlluxioRuntimeSpec.
func (in *AlluxioRuntimeSpec) DeepCopy() *AlluxioRuntimeSpec {
	if in == nil { return nil }
	out := new(AlluxioRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuntime) DeepCopyInto(out *CacheRuntime) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuntime.
func (in *CacheRuntime) DeepCopy() *CacheRuntime {
	if in == nil { return nil }
	out := new(CacheRuntime)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuntimeClass) DeepCopyInto(out *CacheRuntimeClass) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuntimeClass.
func (in *CacheRuntimeClass) DeepCopy() *CacheRuntimeClass {
	if in == nil { return nil }
	out := new(CacheRuntimeClass)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheRuntimeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuntimeClassList) DeepCopyInto(out *CacheRuntimeClassList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuntimeClassList.
func (in *CacheRuntimeClassList) DeepCopy() *CacheRuntimeClassList {
	if in == nil { return nil }
	out := new(CacheRuntimeClassList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheRuntimeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuntimeClientSpec) DeepCopyInto(out *CacheRuntimeClientSpec) {
*out = *in
in.RuntimeComponentCommonSpec.DeepCopyInto(&out.RuntimeComponentCommonSpec)
in.TieredStore.DeepCopyInto(&out.TieredStore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuntimeClientSpec.
func (in *CacheRuntimeClientSpec) DeepCopy() *CacheRuntimeClientSpec {
	if in == nil { return nil }
	out := new(CacheRuntimeClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuntimeList) DeepCopyInto(out *CacheRuntimeList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuntimeList.
func (in *CacheRuntimeList) DeepCopy() *CacheRuntimeList {
	if in == nil { return nil }
	out := new(CacheRuntimeList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CacheRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuntimeMasterSpec) DeepCopyInto(out *CacheRuntimeMasterSpec) {
*out = *in
in.RuntimeComponentCommonSpec.DeepCopyInto(&out.RuntimeComponentCommonSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuntimeMasterSpec.
func (in *CacheRuntimeMasterSpec) DeepCopy() *CacheRuntimeMasterSpec {
	if in == nil { return nil }
	out := new(CacheRuntimeMasterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuntimeSpec) DeepCopyInto(out *CacheRuntimeSpec) {
*out = *in
in.Master.DeepCopyInto(&out.Master)
in.Worker.DeepCopyInto(&out.Worker)
in.Client.DeepCopyInto(&out.Client)
if in.Options != nil {
in, out := &in.Options, &out.Options
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
in.PodMetadata.DeepCopyInto(&out.PodMetadata)
if in.ImagePullSecrets != nil {
in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
if in.Volumes != nil {
in, out := &in.Volumes, &out.Volumes
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuntimeSpec.
func (in *CacheRuntimeSpec) DeepCopy() *CacheRuntimeSpec {
	if in == nil { return nil }
	out := new(CacheRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuntimeStatus) DeepCopyInto(out *CacheRuntimeStatus) {
*out = *in
if in.Conditions != nil {
in, out := &in.Conditions, &out.Conditions
*out = make([]RuntimeCondition, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuntimeStatus.
func (in *CacheRuntimeStatus) DeepCopy() *CacheRuntimeStatus {
	if in == nil { return nil }
	out := new(CacheRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRuntimeWorkerSpec) DeepCopyInto(out *CacheRuntimeWorkerSpec) {
*out = *in
in.RuntimeComponentCommonSpec.DeepCopyInto(&out.RuntimeComponentCommonSpec)
in.TieredStore.DeepCopyInto(&out.TieredStore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRuntimeWorkerSpec.
func (in *CacheRuntimeWorkerSpec) DeepCopy() *CacheRuntimeWorkerSpec {
	if in == nil { return nil }
	out := new(CacheRuntimeWorkerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheableNodeAffinity) DeepCopyInto(out *CacheableNodeAffinity) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheableNodeAffinity.
func (in *CacheableNodeAffinity) DeepCopy() *CacheableNodeAffinity {
	if in == nil { return nil }
	out := new(CacheableNodeAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanCachePolicy) DeepCopyInto(out *CleanCachePolicy) {
*out = *in
if in.GracePeriodSeconds != nil {
in, out := &in.GracePeriodSeconds, &out.GracePeriodSeconds
*out = new(int32)
**out = **in
}
if in.MaxRetryAttempts != nil {
in, out := &in.MaxRetryAttempts, &out.MaxRetryAttempts
*out = new(int32)
**out = **in
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanCachePolicy.
func (in *CleanCachePolicy) DeepCopy() *CleanCachePolicy {
	if in == nil { return nil }
	out := new(CleanCachePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientMetrics) DeepCopyInto(out *ClientMetrics) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientMetrics.
func (in *ClientMetrics) DeepCopy() *ClientMetrics {
	if in == nil { return nil }
	out := new(ClientMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentServiceConfig) DeepCopyInto(out *ComponentServiceConfig) {
*out = *in
if in.Headless != nil {
in, out := &in.Headless, &out.Headless
*out = new(HeadlessRuntimeComponentService)
**out = **in
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentServiceConfig.
func (in *ComponentServiceConfig) DeepCopy() *ComponentServiceConfig {
	if in == nil { return nil }
	out := new(ComponentServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil { return nil }
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapDependencyConfig) DeepCopyInto(out *ConfigMapDependencyConfig) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapDependencyConfig.
func (in *ConfigMapDependencyConfig) DeepCopy() *ConfigMapDependencyConfig {
	if in == nil { return nil }
	out := new(ConfigMapDependencyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRuntimeExtraResource) DeepCopyInto(out *ConfigMapRuntimeExtraResource) {
*out = *in
if in.Data != nil {
in, out := &in.Data, &out.Data
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRuntimeExtraResource.
func (in *ConfigMapRuntimeExtraResource) DeepCopy() *ConfigMapRuntimeExtraResource {
	if in == nil { return nil }
	out := new(ConfigMapRuntimeExtraResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Data) DeepCopyInto(out *Data) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Data.
func (in *Data) DeepCopy() *Data {
	if in == nil { return nil }
	out := new(Data)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataBackup) DeepCopyInto(out *DataBackup) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataBackup.
func (in *DataBackup) DeepCopy() *DataBackup {
	if in == nil { return nil }
	out := new(DataBackup)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataBackupList) DeepCopyInto(out *DataBackupList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataBackupList.
func (in *DataBackupList) DeepCopy() *DataBackupList {
	if in == nil { return nil }
	out := new(DataBackupList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataBackupSpec) DeepCopyInto(out *DataBackupSpec) {
*out = *in
if in.RunAs != nil {
in, out := &in.RunAs, &out.RunAs
*out = new(User)
(*in).DeepCopyInto(*out)
}
if in.RunAfter != nil {
in, out := &in.RunAfter, &out.RunAfter
*out = new(OperationRef)
(*in).DeepCopyInto(*out)
}
if in.TTLSecondsAfterFinished != nil {
in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
*out = new(int32)
**out = **in
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataBackupSpec.
func (in *DataBackupSpec) DeepCopy() *DataBackupSpec {
	if in == nil { return nil }
	out := new(DataBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataClean) DeepCopyInto(out *DataClean) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataClean.
func (in *DataClean) DeepCopy() *DataClean {
	if in == nil { return nil }
	out := new(DataClean)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataClean) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataCleanList) DeepCopyInto(out *DataCleanList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataCleanList.
func (in *DataCleanList) DeepCopy() *DataCleanList {
	if in == nil { return nil }
	out := new(DataCleanList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataCleanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataCleanSpec) DeepCopyInto(out *DataCleanSpec) {
*out = *in
out.Dataset = in.Dataset
if in.TTLSecondsAfterFinished != nil {
in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
*out = new(int32)
**out = **in
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataCleanSpec.
func (in *DataCleanSpec) DeepCopy() *DataCleanSpec {
	if in == nil { return nil }
	out := new(DataCleanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoad) DeepCopyInto(out *DataLoad) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoad.
func (in *DataLoad) DeepCopy() *DataLoad {
	if in == nil { return nil }
	out := new(DataLoad)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataLoad) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoadList) DeepCopyInto(out *DataLoadList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoadList.
func (in *DataLoadList) DeepCopy() *DataLoadList {
	if in == nil { return nil }
	out := new(DataLoadList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataLoadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLoadSpec) DeepCopyInto(out *DataLoadSpec) {
*out = *in
out.Dataset = in.Dataset
if in.Target != nil {
in, out := &in.Target, &out.Target
*out = make([]TargetPath, len(*in))
copy(*out, *in)
}
if in.Options != nil {
in, out := &in.Options, &out.Options
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
in.PodMetadata.DeepCopyInto(&out.PodMetadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLoadSpec.
func (in *DataLoadSpec) DeepCopy() *DataLoadSpec {
	if in == nil { return nil }
	out := new(DataLoadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMigrate) DeepCopyInto(out *DataMigrate) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMigrate.
func (in *DataMigrate) DeepCopy() *DataMigrate {
	if in == nil { return nil }
	out := new(DataMigrate)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataMigrate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMigrateList) DeepCopyInto(out *DataMigrateList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMigrateList.
func (in *DataMigrateList) DeepCopy() *DataMigrateList {
	if in == nil { return nil }
	out := new(DataMigrateList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataMigrateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMigrateSpec) DeepCopyInto(out *DataMigrateSpec) {
*out = *in
out.VersionSpec = in.VersionSpec
in.From.DeepCopyInto(&out.From)
in.To.DeepCopyInto(&out.To)
if in.Options != nil {
in, out := &in.Options, &out.Options
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
in.PodMetadata.DeepCopyInto(&out.PodMetadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMigrateSpec.
func (in *DataMigrateSpec) DeepCopy() *DataMigrateSpec {
	if in == nil { return nil }
	out := new(DataMigrateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProcess) DeepCopyInto(out *DataProcess) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProcess.
func (in *DataProcess) DeepCopy() *DataProcess {
	if in == nil { return nil }
	out := new(DataProcess)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataProcess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProcessList) DeepCopyInto(out *DataProcessList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProcessList.
func (in *DataProcessList) DeepCopy() *DataProcessList {
	if in == nil { return nil }
	out := new(DataProcessList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataProcessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProcessSpec) DeepCopyInto(out *DataProcessSpec) {
*out = *in
out.Dataset = in.Dataset
in.Processor.DeepCopyInto(&out.Processor)
if in.RunAfter != nil {
in, out := &in.RunAfter, &out.RunAfter
*out = new(OperationRef)
(*in).DeepCopyInto(*out)
}
if in.TTLSecondsAfterFinished != nil {
in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
*out = new(int32)
**out = **in
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProcessSpec.
func (in *DataProcessSpec) DeepCopy() *DataProcessSpec {
	if in == nil { return nil }
	out := new(DataProcessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataRestoreLocation) DeepCopyInto(out *DataRestoreLocation) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataRestoreLocation.
func (in *DataRestoreLocation) DeepCopy() *DataRestoreLocation {
	if in == nil { return nil }
	out := new(DataRestoreLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataToMigrate) DeepCopyInto(out *DataToMigrate) {
*out = *in
if in.DataSet != nil {
in, out := &in.DataSet, &out.DataSet
*out = new(DatasetToMigrate)
**out = **in
}
if in.ExternalStorage != nil {
in, out := &in.ExternalStorage, &out.ExternalStorage
*out = new(ExternalStorage)
(*in).DeepCopyInto(*out)
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataToMigrate.
func (in *DataToMigrate) DeepCopy() *DataToMigrate {
	if in == nil { return nil }
	out := new(DataToMigrate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dataset) DeepCopyInto(out *Dataset) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dataset.
func (in *Dataset) DeepCopy() *Dataset {
	if in == nil { return nil }
	out := new(Dataset)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dataset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetCondition) DeepCopyInto(out *DatasetCondition) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetCondition.
func (in *DatasetCondition) DeepCopy() *DatasetCondition {
	if in == nil { return nil }
	out := new(DatasetCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetList) DeepCopyInto(out *DatasetList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetList.
func (in *DatasetList) DeepCopy() *DatasetList {
	if in == nil { return nil }
	out := new(DatasetList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatasetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetSpec) DeepCopyInto(out *DatasetSpec) {
*out = *in
if in.Mounts != nil {
in, out := &in.Mounts, &out.Mounts
*out = make([]Mount, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
if in.Owner != nil {
in, out := &in.Owner, &out.Owner
*out = new(User)
(*in).DeepCopyInto(*out)
}
if in.NodeAffinity != nil {
in, out := &in.NodeAffinity, &out.NodeAffinity
*out = new(CacheableNodeAffinity)
(*in).DeepCopyInto(*out)
}
if in.Tolerations != nil {
in, out := &in.Tolerations, &out.Tolerations
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
if in.AccessModes != nil {
in, out := &in.AccessModes, &out.AccessModes
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
if in.Runtimes != nil {
in, out := &in.Runtimes, &out.Runtimes
*out = make([]Runtime, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
if in.DataRestoreLocation != nil {
in, out := &in.DataRestoreLocation, &out.DataRestoreLocation
*out = new(DataRestoreLocation)
**out = **in
}
if in.SharedOptions != nil {
in, out := &in.SharedOptions, &out.SharedOptions
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.SharedEncryptOptions != nil {
in, out := &in.SharedEncryptOptions, &out.SharedEncryptOptions
*out = make([]EncryptOption, len(*in))
copy(*out, *in)
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetSpec.
func (in *DatasetSpec) DeepCopy() *DatasetSpec {
	if in == nil { return nil }
	out := new(DatasetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetStatus) DeepCopyInto(out *DatasetStatus) {
*out = *in
if in.Mounts != nil {
in, out := &in.Mounts, &out.Mounts
*out = make([]Mount, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
if in.Runtimes != nil {
in, out := &in.Runtimes, &out.Runtimes
*out = make([]Runtime, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
if in.Conditions != nil {
in, out := &in.Conditions, &out.Conditions
*out = make([]DatasetCondition, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetStatus.
func (in *DatasetStatus) DeepCopy() *DatasetStatus {
	if in == nil { return nil }
	out := new(DatasetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetToMigrate) DeepCopyInto(out *DatasetToMigrate) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetToMigrate.
func (in *DatasetToMigrate) DeepCopy() *DatasetToMigrate {
	if in == nil { return nil }
	out := new(DatasetToMigrate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EFCCompTemplateSpec) DeepCopyInto(out *EFCCompTemplateSpec) {
*out = *in
out.Version = in.Version
if in.Properties != nil {
in, out := &in.Properties, &out.Properties
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.Ports != nil {
in, out := &in.Ports, &out.Ports
*out = make(map[string]int, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EFCCompTemplateSpec.
func (in *EFCCompTemplateSpec) DeepCopy() *EFCCompTemplateSpec {
	if in == nil { return nil }
	out := new(EFCCompTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EFCFuseSpec) DeepCopyInto(out *EFCFuseSpec) {
*out = *in
out.Version = in.Version
if in.Properties != nil {
in, out := &in.Properties, &out.Properties
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EFCFuseSpec.
func (in *EFCFuseSpec) DeepCopy() *EFCFuseSpec {
	if in == nil { return nil }
	out := new(EFCFuseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EFCRuntime) DeepCopyInto(out *EFCRuntime) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EFCRuntime.
func (in *EFCRuntime) DeepCopy() *EFCRuntime {
	if in == nil { return nil }
	out := new(EFCRuntime)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EFCRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EFCRuntimeList) DeepCopyInto(out *EFCRuntimeList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EFCRuntimeList.
func (in *EFCRuntimeList) DeepCopy() *EFCRuntimeList {
	if in == nil { return nil }
	out := new(EFCRuntimeList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EFCRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EFCRuntimeSpec) DeepCopyInto(out *EFCRuntimeSpec) {
*out = *in
in.Master.DeepCopyInto(&out.Master)
in.Worker.DeepCopyInto(&out.Worker)
out.InitFuse = in.InitFuse
in.Fuse.DeepCopyInto(&out.Fuse)
in.TieredStore.DeepCopyInto(&out.TieredStore)
out.OSAdvise = in.OSAdvise
in.CleanCachePolicy.DeepCopyInto(&out.CleanCachePolicy)
in.PodMetadata.DeepCopyInto(&out.PodMetadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EFCRuntimeSpec.
func (in *EFCRuntimeSpec) DeepCopy() *EFCRuntimeSpec {
	if in == nil { return nil }
	out := new(EFCRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptOption) DeepCopyInto(out *EncryptOption) {
*out = *in
out.ValueFrom = in.ValueFrom
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptOption.
func (in *EncryptOption) DeepCopy() *EncryptOption {
	if in == nil { return nil }
	out := new(EncryptOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptOptionComponentDependency) DeepCopyInto(out *EncryptOptionComponentDependency) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptOptionComponentDependency.
func (in *EncryptOptionComponentDependency) DeepCopy() *EncryptOptionComponentDependency {
	if in == nil { return nil }
	out := new(EncryptOptionComponentDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptOptionSource) DeepCopyInto(out *EncryptOptionSource) {
*out = *in
out.SecretKeyRef = in.SecretKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptOptionSource.
func (in *EncryptOptionSource) DeepCopy() *EncryptOptionSource {
	if in == nil { return nil }
	out := new(EncryptOptionSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalEndpointSpec) DeepCopyInto(out *ExternalEndpointSpec) {
*out = *in
if in.EncryptOptions != nil {
in, out := &in.EncryptOptions, &out.EncryptOptions
*out = make([]EncryptOption, len(*in))
copy(*out, *in)
}
if in.Options != nil {
in, out := &in.Options, &out.Options
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalEndpointSpec.
func (in *ExternalEndpointSpec) DeepCopy() *ExternalEndpointSpec {
	if in == nil { return nil }
	out := new(ExternalEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalStorage) DeepCopyInto(out *ExternalStorage) {
*out = *in
if in.EncryptOptions != nil {
in, out := &in.EncryptOptions, &out.EncryptOptions
*out = make([]EncryptOption, len(*in))
copy(*out, *in)
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalStorage.
func (in *ExternalStorage) DeepCopy() *ExternalStorage {
	if in == nil { return nil }
	out := new(ExternalStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtraResourcesComponentDependency) DeepCopyInto(out *ExtraResourcesComponentDependency) {
*out = *in
if in.ConfigMaps != nil {
in, out := &in.ConfigMaps, &out.ConfigMaps
*out = make([]ConfigMapDependencyConfig, len(*in))
copy(*out, *in)
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtraResourcesComponentDependency.
func (in *ExtraResourcesComponentDependency) DeepCopy() *ExtraResourcesComponentDependency {
	if in == nil { return nil }
	out := new(ExtraResourcesComponentDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooseFSCompTemplateSpec) DeepCopyInto(out *GooseFSCompTemplateSpec) {
*out = *in
if in.JvmOptions != nil {
in, out := &in.JvmOptions, &out.JvmOptions
*out = make([]string, len(*in))
copy(*out, *in)
}
if in.Properties != nil {
in, out := &in.Properties, &out.Properties
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.Ports != nil {
in, out := &in.Ports, &out.Ports
*out = make(map[string]int, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooseFSCompTemplateSpec.
func (in *GooseFSCompTemplateSpec) DeepCopy() *GooseFSCompTemplateSpec {
	if in == nil { return nil }
	out := new(GooseFSCompTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooseFSFuseSpec) DeepCopyInto(out *GooseFSFuseSpec) {
*out = *in
if in.JvmOptions != nil {
in, out := &in.JvmOptions, &out.JvmOptions
*out = make([]string, len(*in))
copy(*out, *in)
}
if in.Properties != nil {
in, out := &in.Properties, &out.Properties
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.Env != nil {
in, out := &in.Env, &out.Env
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooseFSFuseSpec.
func (in *GooseFSFuseSpec) DeepCopy() *GooseFSFuseSpec {
	if in == nil { return nil }
	out := new(GooseFSFuseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooseFSRuntime) DeepCopyInto(out *GooseFSRuntime) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooseFSRuntime.
func (in *GooseFSRuntime) DeepCopy() *GooseFSRuntime {
	if in == nil { return nil }
	out := new(GooseFSRuntime)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GooseFSRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooseFSRuntimeList) DeepCopyInto(out *GooseFSRuntimeList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooseFSRuntimeList.
func (in *GooseFSRuntimeList) DeepCopy() *GooseFSRuntimeList {
	if in == nil { return nil }
	out := new(GooseFSRuntimeList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GooseFSRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GooseFSRuntimeSpec) DeepCopyInto(out *GooseFSRuntimeSpec) {
*out = *in
out.GooseFSVersion = in.GooseFSVersion
in.Master.DeepCopyInto(&out.Master)
in.JobMaster.DeepCopyInto(&out.JobMaster)
in.Worker.DeepCopyInto(&out.Worker)
in.JobWorker.DeepCopyInto(&out.JobWorker)
in.APIGateway.DeepCopyInto(&out.APIGateway)
in.InitUsers.DeepCopyInto(&out.InitUsers)
in.Fuse.DeepCopyInto(&out.Fuse)
if in.Properties != nil {
in, out := &in.Properties, &out.Properties
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.JvmOptions != nil {
in, out := &in.JvmOptions, &out.JvmOptions
*out = make([]string, len(*in))
copy(*out, *in)
}
in.TieredStore.DeepCopyInto(&out.TieredStore)
out.Data = in.Data
if in.RunAs != nil {
in, out := &in.RunAs, &out.RunAs
*out = new(User)
(*in).DeepCopyInto(*out)
}
in.CleanCachePolicy.DeepCopyInto(&out.CleanCachePolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GooseFSRuntimeSpec.
func (in *GooseFSRuntimeSpec) DeepCopy() *GooseFSRuntimeSpec {
	if in == nil { return nil }
	out := new(GooseFSRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCFSStatus) DeepCopyInto(out *HCFSStatus) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCFSStatus.
func (in *HCFSStatus) DeepCopy() *HCFSStatus {
	if in == nil { return nil }
	out := new(HCFSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadlessRuntimeComponentService) DeepCopyInto(out *HeadlessRuntimeComponentService) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadlessRuntimeComponentService.
func (in *HeadlessRuntimeComponentService) DeepCopy() *HeadlessRuntimeComponentService {
	if in == nil { return nil }
	out := new(HeadlessRuntimeComponentService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitFuseSpec) DeepCopyInto(out *InitFuseSpec) {
*out = *in
out.Version = in.Version
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitFuseSpec.
func (in *InitFuseSpec) DeepCopy() *InitFuseSpec {
	if in == nil { return nil }
	out := new(InitFuseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitUsersSpec) DeepCopyInto(out *InitUsersSpec) {
*out = *in
if in.Env != nil {
in, out := &in.Env, &out.Env
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitUsersSpec.
func (in *InitUsersSpec) DeepCopy() *InitUsersSpec {
	if in == nil { return nil }
	out := new(InitUsersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JindoCompTemplateSpec) DeepCopyInto(out *JindoCompTemplateSpec) {
*out = *in
if in.Properties != nil {
in, out := &in.Properties, &out.Properties
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.Ports != nil {
in, out := &in.Ports, &out.Ports
*out = make(map[string]int, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JindoCompTemplateSpec.
func (in *JindoCompTemplateSpec) DeepCopy() *JindoCompTemplateSpec {
	if in == nil { return nil }
	out := new(JindoCompTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JindoFuseSpec) DeepCopyInto(out *JindoFuseSpec) {
*out = *in
if in.ImagePullSecrets != nil {
in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
if in.Properties != nil {
in, out := &in.Properties, &out.Properties
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.Env != nil {
in, out := &in.Env, &out.Env
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JindoFuseSpec.
func (in *JindoFuseSpec) DeepCopy() *JindoFuseSpec {
	if in == nil { return nil }
	out := new(JindoFuseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JindoRuntime) DeepCopyInto(out *JindoRuntime) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JindoRuntime.
func (in *JindoRuntime) DeepCopy() *JindoRuntime {
	if in == nil { return nil }
	out := new(JindoRuntime)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JindoRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JindoRuntimeList) DeepCopyInto(out *JindoRuntimeList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JindoRuntimeList.
func (in *JindoRuntimeList) DeepCopy() *JindoRuntimeList {
	if in == nil { return nil }
	out := new(JindoRuntimeList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JindoRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JindoRuntimeSpec) DeepCopyInto(out *JindoRuntimeSpec) {
*out = *in
out.JindoVersion = in.JindoVersion
in.Master.DeepCopyInto(&out.Master)
in.Worker.DeepCopyInto(&out.Worker)
in.Fuse.DeepCopyInto(&out.Fuse)
if in.Properties != nil {
in, out := &in.Properties, &out.Properties
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
in.TieredStore.DeepCopyInto(&out.TieredStore)
if in.RunAs != nil {
in, out := &in.RunAs, &out.RunAs
*out = new(User)
(*in).DeepCopyInto(*out)
}
if in.Labels != nil {
in, out := &in.Labels, &out.Labels
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
in.PodMetadata.DeepCopyInto(&out.PodMetadata)
if in.LogConfig != nil {
in, out := &in.LogConfig, &out.LogConfig
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
in.CleanCachePolicy.DeepCopyInto(&out.CleanCachePolicy)
if in.Volumes != nil {
in, out := &in.Volumes, &out.Volumes
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
if in.ImagePullSecrets != nil {
in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JindoRuntimeSpec.
func (in *JindoRuntimeSpec) DeepCopy() *JindoRuntimeSpec {
	if in == nil { return nil }
	out := new(JindoRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobProcessor) DeepCopyInto(out *JobProcessor) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobProcessor.
func (in *JobProcessor) DeepCopy() *JobProcessor {
	if in == nil { return nil }
	out := new(JobProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JuiceFSCompTemplateSpec) DeepCopyInto(out *JuiceFSCompTemplateSpec) {
*out = *in
if in.Ports != nil {
in, out := &in.Ports, &out.Ports
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JuiceFSCompTemplateSpec.
func (in *JuiceFSCompTemplateSpec) DeepCopy() *JuiceFSCompTemplateSpec {
	if in == nil { return nil }
	out := new(JuiceFSCompTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JuiceFSFuseSpec) DeepCopyInto(out *JuiceFSFuseSpec) {
*out = *in
if in.Env != nil {
in, out := &in.Env, &out.Env
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JuiceFSFuseSpec.
func (in *JuiceFSFuseSpec) DeepCopy() *JuiceFSFuseSpec {
	if in == nil { return nil }
	out := new(JuiceFSFuseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JuiceFSRuntime) DeepCopyInto(out *JuiceFSRuntime) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JuiceFSRuntime.
func (in *JuiceFSRuntime) DeepCopy() *JuiceFSRuntime {
	if in == nil { return nil }
	out := new(JuiceFSRuntime)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JuiceFSRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JuiceFSRuntimeList) DeepCopyInto(out *JuiceFSRuntimeList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JuiceFSRuntimeList.
func (in *JuiceFSRuntimeList) DeepCopy() *JuiceFSRuntimeList {
	if in == nil { return nil }
	out := new(JuiceFSRuntimeList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JuiceFSRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JuiceFSRuntimeSpec) DeepCopyInto(out *JuiceFSRuntimeSpec) {
*out = *in
out.JuiceFSVersion = in.JuiceFSVersion
in.InitUsers.DeepCopyInto(&out.InitUsers)
in.Master.DeepCopyInto(&out.Master)
in.Worker.DeepCopyInto(&out.Worker)
in.JobWorker.DeepCopyInto(&out.JobWorker)
in.Fuse.DeepCopyInto(&out.Fuse)
in.TieredStore.DeepCopyInto(&out.TieredStore)
if in.Configs != nil {
in, out := &in.Configs, &out.Configs
*out = new([]string)
if **in != nil {
in, out := *in, *out
*out = make([]string, len(*in))
copy(*out, *in)
}
}
if in.RunAs != nil {
in, out := &in.RunAs, &out.RunAs
*out = new(User)
(*in).DeepCopyInto(*out)
}
if in.Volumes != nil {
in, out := &in.Volumes, &out.Volumes
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
in.PodMetadata.DeepCopyInto(&out.PodMetadata)
in.RuntimeManagement.DeepCopyInto(&out.RuntimeManagement)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JuiceFSRuntimeSpec.
func (in *JuiceFSRuntimeSpec) DeepCopy() *JuiceFSRuntimeSpec {
	if in == nil { return nil }
	out := new(JuiceFSRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Level) DeepCopyInto(out *Level) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Level.
func (in *Level) DeepCopy() *Level {
	if in == nil { return nil }
	out := new(Level)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterSpec) DeepCopyInto(out *MasterSpec) {
*out = *in
in.VineyardCompTemplateSpec.DeepCopyInto(&out.VineyardCompTemplateSpec)
in.ExternalEndpoint.DeepCopyInto(&out.ExternalEndpoint)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterSpec.
func (in *MasterSpec) DeepCopy() *MasterSpec {
	if in == nil { return nil }
	out := new(MasterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediumSource) DeepCopyInto(out *MediumSource) {
*out = *in
if in.ProcessMemory != nil {
in, out := &in.ProcessMemory, &out.ProcessMemory
*out = new(ProcessMemoryMediumSource)
**out = **in
}
if in.Volume != nil {
in, out := &in.Volume, &out.Volume
*out = new(VolumeMediumSource)
(*in).DeepCopyInto(*out)
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediumSource.
func (in *MediumSource) DeepCopy() *MediumSource {
	if in == nil { return nil }
	out := new(MediumSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metadata) DeepCopyInto(out *Metadata) {
*out = *in
in.PodMetadata.DeepCopyInto(&out.PodMetadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metadata.
func (in *Metadata) DeepCopy() *Metadata {
	if in == nil { return nil }
	out := new(Metadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataSyncPolicy) DeepCopyInto(out *MetadataSyncPolicy) {
*out = *in
if in.AutoSync != nil {
in, out := &in.AutoSync, &out.AutoSync
*out = new(bool)
**out = **in
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataSyncPolicy.
func (in *MetadataSyncPolicy) DeepCopy() *MetadataSyncPolicy {
	if in == nil { return nil }
	out := new(MetadataSyncPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mount) DeepCopyInto(out *Mount) {
*out = *in
if in.Options != nil {
in, out := &in.Options, &out.Options
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.EncryptOptions != nil {
in, out := &in.EncryptOptions, &out.EncryptOptions
*out = make([]EncryptOption, len(*in))
copy(*out, *in)
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mount.
func (in *Mount) DeepCopy() *Mount {
	if in == nil { return nil }
	out := new(Mount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountPointStatus) DeepCopyInto(out *MountPointStatus) {
*out = *in
in.Mount.DeepCopyInto(&out.Mount)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountPointStatus.
func (in *MountPointStatus) DeepCopy() *MountPointStatus {
	if in == nil { return nil }
	out := new(MountPointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSAdvise) DeepCopyInto(out *OSAdvise) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSAdvise.
func (in *OSAdvise) DeepCopy() *OSAdvise {
	if in == nil { return nil }
	out := new(OSAdvise)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil { return nil }
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationRef) DeepCopyInto(out *OperationRef) {
*out = *in
out.ObjectRef = in.ObjectRef
in.AffinityStrategy.DeepCopyInto(&out.AffinityStrategy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationRef.
func (in *OperationRef) DeepCopy() *OperationRef {
	if in == nil { return nil }
	out := new(OperationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationStatus) DeepCopyInto(out *OperationStatus) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationStatus.
func (in *OperationStatus) DeepCopy() *OperationStatus {
	if in == nil { return nil }
	out := new(OperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMetadata) DeepCopyInto(out *PodMetadata) {
*out = *in
if in.Labels != nil {
in, out := &in.Labels, &out.Labels
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.Annotations != nil {
in, out := &in.Annotations, &out.Annotations
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMetadata.
func (in *PodMetadata) DeepCopy() *PodMetadata {
	if in == nil { return nil }
	out := new(PodMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Prefer) DeepCopyInto(out *Prefer) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Prefer.
func (in *Prefer) DeepCopy() *Prefer {
	if in == nil { return nil }
	out := new(Prefer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessMemoryMediumSource) DeepCopyInto(out *ProcessMemoryMediumSource) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessMemoryMediumSource.
func (in *ProcessMemoryMediumSource) DeepCopy() *ProcessMemoryMediumSource {
	if in == nil { return nil }
	out := new(ProcessMemoryMediumSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Processor) DeepCopyInto(out *Processor) {
*out = *in
in.PodMetadata.DeepCopyInto(&out.PodMetadata)
if in.Job != nil {
in, out := &in.Job, &out.Job
*out = new(JobProcessor)
(*in).DeepCopyInto(*out)
}
if in.Script != nil {
in, out := &in.Script, &out.Script
*out = new(ScriptProcessor)
(*in).DeepCopyInto(*out)
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Processor.
func (in *Processor) DeepCopy() *Processor {
	if in == nil { return nil }
	out := new(Processor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Require) DeepCopyInto(out *Require) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Require.
func (in *Require) DeepCopy() *Require {
	if in == nil { return nil }
	out := new(Require)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Runtime) DeepCopyInto(out *Runtime) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Runtime.
func (in *Runtime) DeepCopy() *Runtime {
	if in == nil { return nil }
	out := new(Runtime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeComponentCommonSpec) DeepCopyInto(out *RuntimeComponentCommonSpec) {
*out = *in
out.RuntimeVersion = in.RuntimeVersion
if in.Options != nil {
in, out := &in.Options, &out.Options
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
in.PodMetadata.DeepCopyInto(&out.PodMetadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeComponentCommonSpec.
func (in *RuntimeComponentCommonSpec) DeepCopy() *RuntimeComponentCommonSpec {
	if in == nil { return nil }
	out := new(RuntimeComponentCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeComponentDefinition) DeepCopyInto(out *RuntimeComponentDefinition) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeComponentDefinition.
func (in *RuntimeComponentDefinition) DeepCopy() *RuntimeComponentDefinition {
	if in == nil { return nil }
	out := new(RuntimeComponentDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeComponentDependencies) DeepCopyInto(out *RuntimeComponentDependencies) {
*out = *in
if in.EncryptOption != nil {
in, out := &in.EncryptOption, &out.EncryptOption
*out = new(EncryptOptionComponentDependency)
**out = **in
}
if in.ExtraResources != nil {
in, out := &in.ExtraResources, &out.ExtraResources
*out = new(ExtraResourcesComponentDependency)
(*in).DeepCopyInto(*out)
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeComponentDependencies.
func (in *RuntimeComponentDependencies) DeepCopy() *RuntimeComponentDependencies {
	if in == nil { return nil }
	out := new(RuntimeComponentDependencies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeComponentService) DeepCopyInto(out *RuntimeComponentService) {
*out = *in
in.ComponentServiceConfig.DeepCopyInto(&out.ComponentServiceConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeComponentService.
func (in *RuntimeComponentService) DeepCopy() *RuntimeComponentService {
	if in == nil { return nil }
	out := new(RuntimeComponentService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeComponentStatus) DeepCopyInto(out *RuntimeComponentStatus) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeComponentStatus.
func (in *RuntimeComponentStatus) DeepCopy() *RuntimeComponentStatus {
	if in == nil { return nil }
	out := new(RuntimeComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeComponentStatusCollection) DeepCopyInto(out *RuntimeComponentStatusCollection) {
*out = *in
out.Master = in.Master
out.Worker = in.Worker
out.Client = in.Client
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeComponentStatusCollection.
func (in *RuntimeComponentStatusCollection) DeepCopy() *RuntimeComponentStatusCollection {
	if in == nil { return nil }
	out := new(RuntimeComponentStatusCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeCondition) DeepCopyInto(out *RuntimeCondition) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeCondition.
func (in *RuntimeCondition) DeepCopy() *RuntimeCondition {
	if in == nil { return nil }
	out := new(RuntimeCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeExtraResources) DeepCopyInto(out *RuntimeExtraResources) {
*out = *in
if in.ConfigMaps != nil {
in, out := &in.ConfigMaps, &out.ConfigMaps
*out = make([]ConfigMapRuntimeExtraResource, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeExtraResources.
func (in *RuntimeExtraResources) DeepCopy() *RuntimeExtraResources {
	if in == nil { return nil }
	out := new(RuntimeExtraResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeManagement) DeepCopyInto(out *RuntimeManagement) {
*out = *in
in.CleanCachePolicy.DeepCopyInto(&out.CleanCachePolicy)
in.MetadataSyncPolicy.DeepCopyInto(&out.MetadataSyncPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeManagement.
func (in *RuntimeManagement) DeepCopy() *RuntimeManagement {
	if in == nil { return nil }
	out := new(RuntimeManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeStatus) DeepCopyInto(out *RuntimeStatus) {
*out = *in
if in.Conditions != nil {
in, out := &in.Conditions, &out.Conditions
*out = make([]RuntimeCondition, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeStatus.
func (in *RuntimeStatus) DeepCopy() *RuntimeStatus {
	if in == nil { return nil }
	out := new(RuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeTieredStore) DeepCopyInto(out *RuntimeTieredStore) {
*out = *in
if in.Levels != nil {
in, out := &in.Levels, &out.Levels
*out = make([]RuntimeTieredStoreLevel, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeTieredStore.
func (in *RuntimeTieredStore) DeepCopy() *RuntimeTieredStore {
	if in == nil { return nil }
	out := new(RuntimeTieredStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeTieredStoreLevel) DeepCopyInto(out *RuntimeTieredStoreLevel) {
*out = *in
in.Medium.DeepCopyInto(&out.Medium)
if in.Path != nil {
in, out := &in.Path, &out.Path
*out = make([]string, len(*in))
copy(*out, *in)
}
if in.Quota != nil {
in, out := &in.Quota, &out.Quota
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeTieredStoreLevel.
func (in *RuntimeTieredStoreLevel) DeepCopy() *RuntimeTieredStoreLevel {
	if in == nil { return nil }
	out := new(RuntimeTieredStoreLevel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeTopology) DeepCopyInto(out *RuntimeTopology) {
*out = *in
if in.Master != nil {
in, out := &in.Master, &out.Master
*out = new(RuntimeComponentDefinition)
(*in).DeepCopyInto(*out)
}
if in.Worker != nil {
in, out := &in.Worker, &out.Worker
*out = new(RuntimeComponentDefinition)
(*in).DeepCopyInto(*out)
}
if in.Client != nil {
in, out := &in.Client, &out.Client
*out = new(RuntimeComponentDefinition)
(*in).DeepCopyInto(*out)
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeTopology.
func (in *RuntimeTopology) DeepCopy() *RuntimeTopology {
	if in == nil { return nil }
	out := new(RuntimeTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScriptProcessor) DeepCopyInto(out *ScriptProcessor) {
*out = *in
out.VersionSpec = in.VersionSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScriptProcessor.
func (in *ScriptProcessor) DeepCopy() *ScriptProcessor {
	if in == nil { return nil }
	out := new(ScriptProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil { return nil }
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetDataset) DeepCopyInto(out *TargetDataset) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetDataset.
func (in *TargetDataset) DeepCopy() *TargetDataset {
	if in == nil { return nil }
	out := new(TargetDataset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetDatasetWithMountPath) DeepCopyInto(out *TargetDatasetWithMountPath) {
*out = *in
out.TargetDataset = in.TargetDataset
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetDatasetWithMountPath.
func (in *TargetDatasetWithMountPath) DeepCopy() *TargetDatasetWithMountPath {
	if in == nil { return nil }
	out := new(TargetDatasetWithMountPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetPath) DeepCopyInto(out *TargetPath) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetPath.
func (in *TargetPath) DeepCopy() *TargetPath {
	if in == nil { return nil }
	out := new(TargetPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinCompTemplateSpec) DeepCopyInto(out *ThinCompTemplateSpec) {
*out = *in
if in.ImagePullSecrets != nil {
in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
if in.Ports != nil {
in, out := &in.Ports, &out.Ports
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinCompTemplateSpec.
func (in *ThinCompTemplateSpec) DeepCopy() *ThinCompTemplateSpec {
	if in == nil { return nil }
	out := new(ThinCompTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinFuseSpec) DeepCopyInto(out *ThinFuseSpec) {
*out = *in
if in.ImagePullSecrets != nil {
in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
if in.Ports != nil {
in, out := &in.Ports, &out.Ports
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
if in.Env != nil {
in, out := &in.Env, &out.Env
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
if in.Command != nil {
in, out := &in.Command, &out.Command
*out = make([]string, len(*in))
copy(*out, *in)
}
if in.Args != nil {
in, out := &in.Args, &out.Args
*out = make([]string, len(*in))
copy(*out, *in)
}
if in.Options != nil {
in, out := &in.Options, &out.Options
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinFuseSpec.
func (in *ThinFuseSpec) DeepCopy() *ThinFuseSpec {
	if in == nil { return nil }
	out := new(ThinFuseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinRuntime) DeepCopyInto(out *ThinRuntime) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinRuntime.
func (in *ThinRuntime) DeepCopy() *ThinRuntime {
	if in == nil { return nil }
	out := new(ThinRuntime)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThinRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinRuntimeList) DeepCopyInto(out *ThinRuntimeList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinRuntimeList.
func (in *ThinRuntimeList) DeepCopy() *ThinRuntimeList {
	if in == nil { return nil }
	out := new(ThinRuntimeList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThinRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinRuntimeProfile) DeepCopyInto(out *ThinRuntimeProfile) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinRuntimeProfile.
func (in *ThinRuntimeProfile) DeepCopy() *ThinRuntimeProfile {
	if in == nil { return nil }
	out := new(ThinRuntimeProfile)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThinRuntimeProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinRuntimeProfileList) DeepCopyInto(out *ThinRuntimeProfileList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinRuntimeProfileList.
func (in *ThinRuntimeProfileList) DeepCopy() *ThinRuntimeProfileList {
	if in == nil { return nil }
	out := new(ThinRuntimeProfileList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThinRuntimeProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinRuntimeProfileSpec) DeepCopyInto(out *ThinRuntimeProfileSpec) {
*out = *in
if in.ImagePullSecrets != nil {
in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
in.Worker.DeepCopyInto(&out.Worker)
in.Fuse.DeepCopyInto(&out.Fuse)
if in.Volumes != nil {
in, out := &in.Volumes, &out.Volumes
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinRuntimeProfileSpec.
func (in *ThinRuntimeProfileSpec) DeepCopy() *ThinRuntimeProfileSpec {
	if in == nil { return nil }
	out := new(ThinRuntimeProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinRuntimeProfileStatus) DeepCopyInto(out *ThinRuntimeProfileStatus) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinRuntimeProfileStatus.
func (in *ThinRuntimeProfileStatus) DeepCopy() *ThinRuntimeProfileStatus {
	if in == nil { return nil }
	out := new(ThinRuntimeProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThinRuntimeSpec) DeepCopyInto(out *ThinRuntimeSpec) {
*out = *in
in.Worker.DeepCopyInto(&out.Worker)
in.Fuse.DeepCopyInto(&out.Fuse)
in.TieredStore.DeepCopyInto(&out.TieredStore)
if in.RunAs != nil {
in, out := &in.RunAs, &out.RunAs
*out = new(User)
(*in).DeepCopyInto(*out)
}
if in.Volumes != nil {
in, out := &in.Volumes, &out.Volumes
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
in.RuntimeManagement.DeepCopyInto(&out.RuntimeManagement)
if in.ImagePullSecrets != nil {
in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThinRuntimeSpec.
func (in *ThinRuntimeSpec) DeepCopy() *ThinRuntimeSpec {
	if in == nil { return nil }
	out := new(ThinRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TieredStore) DeepCopyInto(out *TieredStore) {
*out = *in
if in.Levels != nil {
in, out := &in.Levels, &out.Levels
*out = make([]Level, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TieredStore.
func (in *TieredStore) DeepCopy() *TieredStore {
	if in == nil { return nil }
	out := new(TieredStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *User) DeepCopyInto(out *User) {
*out = *in
if in.UID != nil {
in, out := &in.UID, &out.UID
*out = new(int64)
**out = **in
}
if in.GID != nil {
in, out := &in.GID, &out.GID
*out = new(int64)
**out = **in
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new User.
func (in *User) DeepCopy() *User {
	if in == nil { return nil }
	out := new(User)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionSpec) DeepCopyInto(out *VersionSpec) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionSpec.
func (in *VersionSpec) DeepCopy() *VersionSpec {
	if in == nil { return nil }
	out := new(VersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VineyardClientSocketSpec) DeepCopyInto(out *VineyardClientSocketSpec) {
*out = *in
if in.Env != nil {
in, out := &in.Env, &out.Env
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VineyardClientSocketSpec.
func (in *VineyardClientSocketSpec) DeepCopy() *VineyardClientSocketSpec {
	if in == nil { return nil }
	out := new(VineyardClientSocketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VineyardCompTemplateSpec) DeepCopyInto(out *VineyardCompTemplateSpec) {
*out = *in
if in.NodeSelector != nil {
in, out := &in.NodeSelector, &out.NodeSelector
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.Ports != nil {
in, out := &in.Ports, &out.Ports
*out = make(map[string]int, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.Env != nil {
in, out := &in.Env, &out.Env
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
if in.Options != nil {
in, out := &in.Options, &out.Options
*out = make(map[string]string, len(*in))
for key, val := range *in {
(*out)[key] = val
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VineyardCompTemplateSpec.
func (in *VineyardCompTemplateSpec) DeepCopy() *VineyardCompTemplateSpec {
	if in == nil { return nil }
	out := new(VineyardCompTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VineyardRuntime) DeepCopyInto(out *VineyardRuntime) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VineyardRuntime.
func (in *VineyardRuntime) DeepCopy() *VineyardRuntime {
	if in == nil { return nil }
	out := new(VineyardRuntime)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VineyardRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VineyardRuntimeList) DeepCopyInto(out *VineyardRuntimeList) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VineyardRuntimeList.
func (in *VineyardRuntimeList) DeepCopy() *VineyardRuntimeList {
	if in == nil { return nil }
	out := new(VineyardRuntimeList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VineyardRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VineyardRuntimeSpec) DeepCopyInto(out *VineyardRuntimeSpec) {
*out = *in
in.Master.DeepCopyInto(&out.Master)
in.Worker.DeepCopyInto(&out.Worker)
in.Fuse.DeepCopyInto(&out.Fuse)
in.TieredStore.DeepCopyInto(&out.TieredStore)
in.PodMetadata.DeepCopyInto(&out.PodMetadata)
if in.Volumes != nil {
in, out := &in.Volumes, &out.Volumes
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VineyardRuntimeSpec.
func (in *VineyardRuntimeSpec) DeepCopy() *VineyardRuntimeSpec {
	if in == nil { return nil }
	out := new(VineyardRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeMediumSource) DeepCopyInto(out *VolumeMediumSource) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeMediumSource.
func (in *VolumeMediumSource) DeepCopy() *VolumeMediumSource {
	if in == nil { return nil }
	out := new(VolumeMediumSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSource) DeepCopyInto(out *VolumeSource) {
*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSource.
func (in *VolumeSource) DeepCopy() *VolumeSource {
	if in == nil { return nil }
	out := new(VolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitingStatus) DeepCopyInto(out *WaitingStatus) {
*out = *in
if in.OperationComplete != nil {
in, out := &in.OperationComplete, &out.OperationComplete
*out = new(bool)
**out = **in
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitingStatus.
func (in *WaitingStatus) DeepCopy() *WaitingStatus {
	if in == nil { return nil }
	out := new(WaitingStatus)
	in.DeepCopyInto(out)
	return out
}

