/*
  Copyright 2026 The Fluid Authors.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

package engine

import (
	datav1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	"github.com/fluid-cloudnative/fluid/pkg/common"
	"github.com/pkg/errors"
)

// workersOnlyArchApi handles the Workers-Only (P2P) runtime architecture.
// Operations (report summary) are executed on a worker pod, and configuration is
// read from the Worker topology definition.
type workersOnlyArchApi struct {
	name         string
	namespace    string
	runtimeClass *datav1alpha1.CacheRuntimeClass
}

func (h *workersOnlyArchApi) GetExecutionPodInfo() (podName string, containerName string, err error) {
	runtimeClass := h.runtimeClass
	// pod name is auto generated by StatefulSet. we just takes the first pod.
	podName = common.GetCacheComponentName(h.name, common.ComponentTypeWorker) + "-0"

	// fluid assumes the first container is the main container.
	if runtimeClass == nil || runtimeClass.Topology == nil || runtimeClass.Topology.Worker == nil ||
		len(runtimeClass.Topology.Worker.Template.Spec.Containers) == 0 {
		return "", "", errors.New("no container in worker pod template")
	}
	containerName = runtimeClass.Topology.Worker.Template.Spec.Containers[0].Name
	return
}

func (h *workersOnlyArchApi) GetExecutionEntries() *datav1alpha1.ExecutionEntries {
	runtimeClass := h.runtimeClass

	if runtimeClass == nil || runtimeClass.Topology == nil || runtimeClass.Topology.Worker == nil {
		return nil
	}
	return runtimeClass.Topology.Worker.ExecutionEntries
}

func (h *workersOnlyArchApi) IsMountUFSSupported() bool {
	return false
}
