/*
  Copyright 2026 The Fluid Authors.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

package engine

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	datav1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	"github.com/fluid-cloudnative/fluid/pkg/common"
	"github.com/fluid-cloudnative/fluid/pkg/utils"
	"github.com/fluid-cloudnative/fluid/pkg/utils/kubeclient"
	"github.com/pkg/errors"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func (e *CacheEngine) createRuntimeConfigMaps(ctx context.Context, runtimeClass *datav1alpha1.CacheRuntimeClass) error {
	runtime, err := e.getRuntime()
	if err != nil {
		return err
	}

	var True = true
	owner := []metav1.OwnerReference{
		{
			APIVersion:         runtime.APIVersion,
			Kind:               runtime.Kind,
			Name:               runtime.Name,
			UID:                runtime.UID,
			Controller:         &True,
			BlockOwnerDeletion: &True,
		},
	}

	// create the config map defined in CacheRuntimeClass ExtraResources, runtimeClass PodTemplate can use these.
	err = e.createConfigMapInRuntimeClass(ctx, &runtimeClass.ExtraResources, owner)
	if err != nil {
		return err
	}

	// create the config map generated by fluid, automatically mounted in component pods.
	err = e.createRuntimeValueConfigMap(ctx, runtime, owner)
	return err
}

// create if not exists
func (e *CacheEngine) createConfigMapInRuntimeClass(ctx context.Context, extraResources *datav1alpha1.RuntimeExtraResources, owner []metav1.OwnerReference) error {
	if extraResources.ConfigMaps == nil {
		return nil
	}

	for _, configMap := range extraResources.ConfigMaps {
		cm, err := kubeclient.GetConfigmapByNameWithContext(ctx, e.Client, configMap.Name, e.namespace)
		if err != nil {
			return err
		}
		if cm == nil {
			err = kubeclient.CreateConfigMapWithOwnerWithContext(ctx, e.Client, configMap.Name, e.namespace, configMap.Data, owner)
			if err != nil {
				return err
			}
			e.Log.Info("Create ConfigMap succeed", "name", configMap.Name, "namespace", e.namespace)
		}
	}
	return nil
}

// create if not exists
func (e *CacheEngine) createRuntimeValueConfigMap(ctx context.Context, runtime *datav1alpha1.CacheRuntime, owner []metav1.OwnerReference) error {
	configMap, err := kubeclient.GetConfigmapByNameWithContext(ctx, e.Client, common.GetCacheRuntimeConfigConfigMapName(e.name), e.namespace)
	if err != nil {
		return err
	}
	// create if not exists
	if configMap != nil {
		return nil
	}
	data, err := e.generateRuntimeConfigData(ctx, runtime)
	if err != nil {
		return errors.Wrap(err, "failed to generate runtime config")
	}

	return kubeclient.CreateConfigMapWithOwnerWithContext(ctx, e.Client, common.GetCacheRuntimeConfigConfigMapName(e.name), e.namespace, data, owner)
}

// generateRuntimeConfigData generate the data in the config map for runtime config
func (e *CacheEngine) generateRuntimeConfigData(ctx context.Context, runtime *datav1alpha1.CacheRuntime) (map[string]string, error) {
	dataset, err := utils.GetDatasetWithContext(ctx, e.Client, e.name, e.namespace)
	if err != nil {
		return nil, err
	}
	runtimeClass, err := e.getRuntimeClass(runtime.Spec.RuntimeClassName)
	if err != nil {
		return nil, err
	}
	var mounts []common.MountConfig
	for _, m := range dataset.Spec.Mounts {
		mountCg := common.MountConfig{
			Name:       m.Name,
			MountPoint: m.MountPoint,
			ReadOnly:   m.ReadOnly,
			Shared:     m.Shared,
			// m.Path may be empty.
			Path: utils.UFSPathBuilder{}.GenUFSPathInUnifiedNamespace(m),
		}
		options, encryptOptions, err := e.generateDatasetMountOptions(&m, dataset.Spec.SharedEncryptOptions, dataset.Spec.SharedOptions)
		if err != nil {
			return nil, err
		}
		mountCg.Options = options
		mountCg.EncryptOptions = encryptOptions

		mounts = append(mounts, mountCg)
	}

	config := common.CacheRuntimeConfig{
		Mounts:      mounts,
		AccessModes: dataset.Spec.AccessModes,
		TargetPath:  e.getFuseMountPoint(),
	}
	if len(config.AccessModes) == 0 {
		config.AccessModes = []corev1.PersistentVolumeAccessMode{corev1.ReadOnlyMany}
	}

	if runtimeClass.Topology.Master != nil && !runtime.Spec.Master.Disabled {
		config.Master = &common.CacheRuntimeComponentConfig{
			Enabled:  true,
			Name:     common.GetCacheComponentName(e.name, common.ComponentTypeMaster),
			Replicas: runtime.Spec.Master.Replicas,
			Options: utils.UnionMapsWithOverride(
				utils.UnionMapsWithOverride(runtimeClass.Topology.Master.Options, runtime.Spec.Options), runtime.Spec.Master.Options),
		}
		if runtimeClass.Topology.Master.Service.Headless != nil {
			config.Master.Service = common.CacheRuntimeComponentServiceConfig{
				Name: GetComponentServiceName(e.name, common.ComponentTypeMaster),
			}
		}
	}
	if runtimeClass.Topology.Worker != nil && !runtime.Spec.Worker.Disabled {
		config.Worker = &common.CacheRuntimeComponentConfig{
			Enabled:  true,
			Name:     common.GetCacheComponentName(e.name, common.ComponentTypeWorker),
			Replicas: runtime.Spec.Worker.Replicas,
			Options: utils.UnionMapsWithOverride(
				utils.UnionMapsWithOverride(runtimeClass.Topology.Worker.Options, runtime.Spec.Options), runtime.Spec.Worker.Options),
		}
		if runtimeClass.Topology.Worker.Service.Headless != nil {
			config.Worker.Service = common.CacheRuntimeComponentServiceConfig{
				Name: GetComponentServiceName(e.name, common.ComponentTypeWorker),
			}
		}
		// Extract tiered store configuration for worker
		config.Worker.TieredStoreLevels = e.extractTieredStoreLevels(&runtime.Spec.Worker.TieredStore)
	}
	if runtimeClass.Topology.Client != nil && !runtime.Spec.Client.Disabled {
		config.Client = &common.CacheRuntimeComponentConfig{
			Enabled: true,
			Name:    common.GetCacheComponentName(e.name, common.ComponentTypeClient),
			// Replicas: 1,
			Options: utils.UnionMapsWithOverride(
				utils.UnionMapsWithOverride(runtimeClass.Topology.Client.Options, runtime.Spec.Options), runtime.Spec.Client.Options),
		}
		if runtimeClass.Topology.Client.Service.Headless != nil {
			config.Client.Service = common.CacheRuntimeComponentServiceConfig{
				Name: GetComponentServiceName(e.name, common.ComponentTypeClient),
			}
		}
		// Extract tiered store configuration for client
		config.Client.TieredStoreLevels = e.extractTieredStoreLevels(&runtime.Spec.Client.TieredStore)
	}

	b, _ := json.Marshal(config)
	sh, err := e.generateRuntimeSh(&config)
	if err != nil {
		return nil, errors.Wrap(err, "failed to generate runtime.sh")
	}
	data := map[string]string{
		// key can not be modified, will be mounted as a file using by runtime.
		e.getRuntimeConfigFileName(): string(b),
		e.getRuntimeShFileName():     sh,
	}
	return data, nil
}

// extractTieredStoreLevels extracts tiered store configuration from RuntimeTieredStore
// and converts it to TieredStoreLevelConfig for the ConfigMap
func (e *CacheEngine) extractTieredStoreLevels(tieredStore *datav1alpha1.RuntimeTieredStore) []common.TieredStoreLevelConfig {
	if tieredStore == nil || len(tieredStore.Levels) == 0 {
		return nil
	}

	var levels []common.TieredStoreLevelConfig

	for levelIndex, level := range tieredStore.Levels {
		// Determine medium type and extract corresponding configuration
		levelConfig := common.TieredStoreLevelConfig{
			High: level.High,
			Low:  level.Low,
		}
		// some cache system like curvine need set the medium type
		// default HDD, currently only use MEM and HDD.
		levelConfig.MediumType = common.HDD
		if level.ProcessMemory != nil {
			levelConfig.MediumType = common.Memory
			levelConfig.MountPaths = []string{GetMemoryTieredStoreMountPath(levelIndex)}
			levelConfig.Quotas = []string{level.ProcessMemory.Quota.String()}
		} else if level.HostPath != nil {
			// Generate mount paths for all host paths
			var mountPaths []string
			for pathIndex := range level.HostPath.Paths {
				mountPaths = append(mountPaths, GetHostPathTieredStoreMountPath(levelIndex, pathIndex))
			}
			levelConfig.MountPaths = mountPaths
			// Convert quotas to string array
			var quotas []string
			for _, quota := range level.HostPath.Quotas {
				quotas = append(quotas, quota.String())
			}
			levelConfig.Quotas = quotas

		} else if level.EmptyDir != nil {
			// MEM medium
			if level.EmptyDir.Medium == corev1.StorageMediumMemory {
				levelConfig.MediumType = common.Memory
			}
			levelConfig.MountPaths = []string{GetEmptyDirTieredStoreMountPath(levelIndex)}
			levelConfig.Quotas = []string{level.EmptyDir.Quota.String()}
		}

		levels = append(levels, levelConfig)
	}

	return levels
}

// generateRuntimeSh flattens the runtime config into a runtime.sh script, so that FUSE-less
// clients (like Mooncake) can source it directly to get the runtime configuration.
func (e *CacheEngine) generateRuntimeSh(config *common.CacheRuntimeConfig) (string, error) {
	var sb strings.Builder
	sb.WriteString("#!/bin/sh\n")
	sb.WriteString("# Generated by Fluid. DO NOT EDIT.\n")

	writeShExport(&sb, "RUNTIME_TARGETPATH", config.TargetPath)

	accessModes := make([]string, 0, len(config.AccessModes))
	for _, mode := range config.AccessModes {
		accessModes = append(accessModes, string(mode))
	}
	writeShSlice(&sb, "RUNTIME_ACCESSMODES", "RUNTIME_ACCESSMODE", accessModes)

	writeShExport(&sb, "MOUNTS_COUNT", strconv.Itoa(len(config.Mounts)))
	for i, mount := range config.Mounts {
		prefix := fmt.Sprintf("MOUNT_%d", i)
		writeShExport(&sb, prefix+"_NAME", mount.Name)
		writeShExport(&sb, prefix+"_PATH", mount.Path)
		writeShExport(&sb, prefix+"_MOUNTPOINT", mount.MountPoint)
		writeShExport(&sb, prefix+"_READONLY", strconv.FormatBool(mount.ReadOnly))
		writeShExport(&sb, prefix+"_SHARED", strconv.FormatBool(mount.Shared))
		if err := writeShMap(&sb, prefix+"_OPTIONS", mount.Options); err != nil {
			return "", err
		}
		if err := writeShMap(&sb, prefix+"_ENCRYPTOPTIONS", mount.EncryptOptions); err != nil {
			return "", err
		}
	}

	components := []struct {
		prefix string
		config *common.CacheRuntimeComponentConfig
	}{
		{"MASTER", config.Master},
		{"WORKER", config.Worker},
		{"CLIENT", config.Client},
	}
	for _, component := range components {
		if err := writeComponentSh(&sb, component.prefix, component.config); err != nil {
			return "", err
		}
	}

	return sb.String(), nil
}

// writeComponentSh writes the exports of a single component. A component the topology leaves out
// is written from a zero value rather than skipped, so that the same variables exist whatever the
// topology: a consumer running under "set -u" can read any of them, and tells an absent component
// from a present one through the ENABLED flag alone.
func writeComponentSh(sb *strings.Builder, prefix string, config *common.CacheRuntimeComponentConfig) error {
	if config == nil {
		config = &common.CacheRuntimeComponentConfig{}
	}

	writeShExport(sb, prefix+"_ENABLED", strconv.FormatBool(config.Enabled))
	writeShExport(sb, prefix+"_NAME", config.Name)
	writeShExport(sb, prefix+"_REPLICAS", strconv.Itoa(int(config.Replicas)))
	writeShExport(sb, prefix+"_SERVICE_NAME", config.Service.Name)
	if err := writeShMap(sb, prefix+"_OPTIONS", config.Options); err != nil {
		return err
	}

	writeShExport(sb, prefix+"_TIEREDSTORE_LEVELS_COUNT", strconv.Itoa(len(config.TieredStoreLevels)))
	for i, level := range config.TieredStoreLevels {
		levelPrefix := fmt.Sprintf("%s_TIEREDSTORE_LEVEL_%d", prefix, i)
		writeShExport(sb, levelPrefix+"_MEDIUMTYPE", string(level.MediumType))
		writeShSlice(sb, levelPrefix+"_MOUNTPATHS", levelPrefix+"_MOUNTPATH", level.MountPaths)
		writeShSlice(sb, levelPrefix+"_QUOTAS", levelPrefix+"_QUOTA", level.Quotas)
		writeShExport(sb, levelPrefix+"_HIGH", level.High)
		writeShExport(sb, levelPrefix+"_LOW", level.Low)
	}
	return nil
}

// writeShSlice exports a string slice the way mounts are exported: a count, then one variable
// per element. Joining on a separator would be ambiguous, because a mount path or a quota may
// legally contain it. MOUNTPATHS and QUOTAS are also paired by position, so a single stray
// separator would shift the pairing without any error.
func writeShSlice(sb *strings.Builder, plural, singular string, values []string) {
	writeShExport(sb, plural+"_COUNT", strconv.Itoa(len(values)))
	for i, value := range values {
		writeShExport(sb, fmt.Sprintf("%s_%d", singular, i), value)
	}
}

// writeShMap exports a map as a JSON string. json.Marshal sorts the map keys, so the generated
// script stays stable across reconciles.
func writeShMap(sb *strings.Builder, key string, m map[string]string) error {
	if len(m) == 0 {
		writeShExport(sb, key, "{}")
		return nil
	}
	b, err := json.Marshal(m)
	if err != nil {
		return errors.Wrapf(err, "failed to marshal %s", key)
	}
	writeShExport(sb, key, string(b))
	return nil
}

// writeShExport writes a single "export KEY='VALUE'" line. The value is wrapped in single quotes
// so that the shell takes it literally, no matter what the user put in the dataset spec.
func writeShExport(sb *strings.Builder, key, value string) {
	sb.WriteString("export ")
	sb.WriteString(key)
	sb.WriteString("=")
	sb.WriteString("'" + strings.ReplaceAll(value, "'", `'\''`) + "'")
	sb.WriteString("\n")
}
