/*
  Copyright 2026 The Fluid Authors.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

package engine

import (
	"encoding/json"

	datav1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	"github.com/fluid-cloudnative/fluid/pkg/common"
	"github.com/fluid-cloudnative/fluid/pkg/utils"
	"github.com/fluid-cloudnative/fluid/pkg/utils/kubeclient"
	"github.com/pkg/errors"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func (e *CacheEngine) createRuntimeConfigMaps(runtimeClass *datav1alpha1.CacheRuntimeClass) error {
	runtime, err := e.getRuntime()
	if err != nil {
		return err
	}

	var True = true
	owner := []metav1.OwnerReference{
		{
			APIVersion:         runtime.APIVersion,
			Kind:               runtime.Kind,
			Name:               runtime.Name,
			UID:                runtime.UID,
			Controller:         &True,
			BlockOwnerDeletion: &True,
		},
	}

	// create the config map defined in CacheRuntimeClass ExtraResources, runtimeClass PodTemplate can use these.
	err = e.createConfigMapInRuntimeClass(&runtimeClass.ExtraResources, owner)
	if err != nil {
		return err
	}

	// create the config map generated by fluid, automatically mounted in component pods.
	err = e.createRuntimeValueConfigMap(runtime, owner)
	return err
}

// create if not exists
func (e *CacheEngine) createConfigMapInRuntimeClass(extraResources *datav1alpha1.RuntimeExtraResources, owner []metav1.OwnerReference) error {
	if extraResources.ConfigMaps == nil {
		return nil
	}

	for _, configMap := range extraResources.ConfigMaps {
		cm, err := kubeclient.GetConfigmapByName(e.Client, configMap.Name, e.namespace)
		if err != nil {
			return err
		}
		if cm == nil {
			err = kubeclient.CreateConfigMapWithOwner(e.Client, configMap.Name, e.namespace, configMap.Data, owner)
			if err != nil {
				return err
			}
			e.Log.Info("Create ConfigMap succeed", "name", configMap.Name, "namespace", e.namespace)
		}
	}
	return nil
}

// create if not exists
func (e *CacheEngine) createRuntimeValueConfigMap(runtime *datav1alpha1.CacheRuntime, owner []metav1.OwnerReference) error {
	configMap, err := kubeclient.GetConfigmapByName(e.Client, e.getRuntimeConfigConfigMapName(), e.namespace)
	if err != nil {
		return err
	}
	// create if not exists
	if configMap != nil {
		return nil
	}
	data, err := e.generateRuntimeConfigData(runtime)
	if err != nil {
		return errors.Wrap(err, "failed to generate runtime config")
	}

	return kubeclient.CreateConfigMapWithOwner(e.Client, e.getRuntimeConfigConfigMapName(), e.namespace, data, owner)
}

// generateRuntimeConfigData generate the data in the config map for runtime config
func (e *CacheEngine) generateRuntimeConfigData(runtime *datav1alpha1.CacheRuntime) (map[string]string, error) {
	dataset, err := utils.GetDataset(e.Client, e.name, e.namespace)
	if err != nil {
		return nil, err
	}

	runtimeClass, err := e.getRuntimeClass(runtime.Spec.RuntimeClassName)
	if err != nil {
		return nil, err
	}

	var mounts []common.MountConfig
	for _, m := range dataset.Spec.Mounts {
		mountCg := common.MountConfig{
			Name:       m.Name,
			MountPoint: m.MountPoint,
			ReadOnly:   m.ReadOnly,
			Shared:     m.Shared,
			Path:       m.Path,
		}
		options, encryptOptions, err := e.generateDatasetMountOptions(&m, dataset.Spec.SharedEncryptOptions, dataset.Spec.SharedOptions)
		if err != nil {
			return nil, err
		}
		mountCg.Options = options
		mountCg.EncryptOptions = encryptOptions

		mounts = append(mounts, mountCg)
	}

	config := common.CacheRuntimeConfig{
		Mounts:      mounts,
		AccessModes: dataset.Spec.AccessModes,
		TargetPath:  e.getFuseMountPoint(),
	}
	if len(config.AccessModes) == 0 {
		config.AccessModes = []corev1.PersistentVolumeAccessMode{corev1.ReadOnlyMany}
	}

	if !runtime.Spec.Master.Disabled {
		config.Master = &common.CacheRuntimeComponentConfig{
			Enabled:  true,
			Name:     GetComponentName(e.name, common.ComponentTypeMaster),
			Replicas: runtime.Spec.Master.Replicas,
			Options: utils.UnionMapsWithOverride(
				utils.UnionMapsWithOverride(runtimeClass.Topology.Master.Options, runtime.Spec.Options), runtime.Spec.Master.Options),
		}
		if runtimeClass.Topology.Master.Service.Headless != nil {
			config.Master.Service = common.CacheRuntimeComponentServiceConfig{
				Name: GetComponentServiceName(e.name, common.ComponentTypeMaster),
			}
		}
	}
	if !runtime.Spec.Worker.Disabled {
		config.Worker = &common.CacheRuntimeComponentConfig{
			Enabled:  true,
			Name:     GetComponentName(e.name, common.ComponentTypeWorker),
			Replicas: runtime.Spec.Worker.Replicas,
			Options: utils.UnionMapsWithOverride(
				utils.UnionMapsWithOverride(runtimeClass.Topology.Worker.Options, runtime.Spec.Options), runtime.Spec.Worker.Options),
		}
		if runtimeClass.Topology.Worker.Service.Headless != nil {
			config.Worker.Service = common.CacheRuntimeComponentServiceConfig{
				Name: GetComponentServiceName(e.name, common.ComponentTypeWorker),
			}
		}
	}
	if !runtime.Spec.Client.Disabled {
		config.Client = &common.CacheRuntimeComponentConfig{
			Enabled: true,
			Name:    GetComponentName(e.name, common.ComponentTypeClient),
			// Replicas: 1,
			Options: utils.UnionMapsWithOverride(
				utils.UnionMapsWithOverride(runtimeClass.Topology.Client.Options, runtime.Spec.Options), runtime.Spec.Client.Options),
		}
		if runtimeClass.Topology.Client.Service.Headless != nil {
			config.Client.Service = common.CacheRuntimeComponentServiceConfig{
				Name: GetComponentServiceName(e.name, common.ComponentTypeClient),
			}
		}
	}

	b, _ := json.Marshal(config)
	data := map[string]string{
		// key can not be modified, will be mounted as a file using by runtime.
		e.getRuntimeConfigFileName(): string(b),
	}
	return data, nil
}
