/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	datafluidiov1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	versioned "github.com/fluid-cloudnative/fluid/pkg/apis/client/clientset/versioned"
	internalinterfaces "github.com/fluid-cloudnative/fluid/pkg/apis/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/fluid-cloudnative/fluid/pkg/apis/client/listers/data.fluid.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GooseFSRuntimeInformer provides access to a shared informer and lister for
// GooseFSRuntimes.
type GooseFSRuntimeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GooseFSRuntimeLister
}

type gooseFSRuntimeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGooseFSRuntimeInformer constructs a new informer for GooseFSRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGooseFSRuntimeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGooseFSRuntimeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGooseFSRuntimeInformer constructs a new informer for GooseFSRuntime type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGooseFSRuntimeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DataV1alpha1().GooseFSRuntimes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DataV1alpha1().GooseFSRuntimes(namespace).Watch(context.TODO(), options)
			},
		},
		&datafluidiov1alpha1.GooseFSRuntime{},
		resyncPeriod,
		indexers,
	)
}

func (f *gooseFSRuntimeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGooseFSRuntimeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *gooseFSRuntimeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&datafluidiov1alpha1.GooseFSRuntime{}, f.defaultInformer)
}

func (f *gooseFSRuntimeInformer) Lister() v1alpha1.GooseFSRuntimeLister {
	return v1alpha1.NewGooseFSRuntimeLister(f.Informer().GetIndexer())
}
