{
 "title": "JindoRuntime",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "数据读取详情",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "jindofsx_ns_local_read_bytes_total / (1024 * 1024)",
     "legendFormat": "短路读"
    },
    {
     "expr": "jindofsx_ns_remote_read_bytes_total / (1024 * 1024) ",
     "legendFormat": "远端读"
    },
    {
     "expr": "jindofsx_ns_backend_read_bytes_total / (1024 * 1024)",
     "legendFormat": "底层读"
    },
    {
     "expr": "jindofsx_ns_slicelet_read_bytes_total / (1024 * 1024)",
     "legendFormat": "小文件读"
    }
   ]
  },
  {
   "title": "local read(per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "jindofsx_ns_local_read_bytes_total_window / (1024*1024)",
     "legendFormat": "短路读"
    }
   ]
  },
  {
   "title": "remote read (per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "jindofsx_ns_remote_read_bytes_total_window / (1024 * 1024)",
     "legendFormat": "远端读"
    }
   ]
  },
  {
   "title": "backend read(Per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "jindofsx_ns_backend_read_bytes_total_window / (1024 * 1024)",
     "legendFormat": "底层读"
    }
   ]
  },
  {
   "title": "磁盘缓存",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "jindofsx_ns_total_disk_cap / (1024 * 1024)",
     "legendFormat": "磁盘总容量"
    },
    {
     "expr": "jindofsx_ns_total_used_disk_cap / (1024 * 1024)",
     "legendFormat": "磁盘缓存使用量"
    }
   ]
  },
  {
   "title": "缓存命中率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(jindofsx_ns_local_read_bytes_total + jindofsx_ns_remote_read_bytes_total) * 100 / (jindofsx_ns_local_read_bytes_total + jindofsx_ns_remote_read_bytes_total + jindofsx_ns_backend_read_bytes_total)",
     "legendFormat": "缓存命中率"
    }
   ]
  },
  {
   "title": "worker数量",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jindofsx_ns_total_stsnodes_num" }
   ]
  }
 ]
}