{
 "title": "Fluid-GooseFS-Runtime",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "goosefs_datasource",
    "label": "The datasource of goosefs prometheus",
    "query": "prometheus"
   },
   { "name": "masters", "query": "master" },
   {
    "name": "workers",
    "label": "The prometheus job_name including worker nodes",
    "query": "goosefs worker"
   },
   {
    "name": "goosefs_user",
    "label": "User of runtime",
    "query": "metrics(Master_getConfiguration_User)"
   },
   { "name": "instance", "query": "label_values(instance)" },
   { "name": "fluid_runtime", "query": "label_values(fluid_runtime)" },
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  { "title": "GooseFS IO Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes Read Local (Total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_BytesReadLocal{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "Bytes Read Local"
    }
   ]
  },
  {
   "title": "Bytes Read Remote (Total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_BytesReadAlluxio{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "Bytes Read Local"
    }
   ]
  },
  {
   "title": "Bytes Read UFS(Total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_BytesReadUfsAll{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "Bytes Read UFS"
    }
   ]
  },
  {
   "title": "Live Workers",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Cluster_Workers{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Bytes Read Remote (Throughput)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_BytesReadAlluxioThroughput{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "Bytes Read Remote (Per Minute)"
    }
   ]
  },
  {
   "title": "Bytes Read Local (Throughput)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_BytesReadLocalThroughput{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "Bytes Read Local (Per Minute)"
    }
   ]
  },
  {
   "title": "Bytes Read UFS (Throughput)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_BytesReadUfsThroughput{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "Bytes Read Ufs (Per Minute)"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "% GooseFS Space Used",
   "type": "graph",
   "description": "Displays the percentage of free GooseFS storage with thresholds from 100-50%, 50-10%, and 10-0%",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(Cluster_CapacityUsed{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}) / Cluster_CapacityTotal{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Used Percentage"
    }
   ]
  },
  {
   "title": "GooseFS Space Used",
   "type": "graph",
   "description": "Displays the percentage of free GooseFS storage with thresholds from 100-50%, 50-10%, and 10-0%",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "Cluster_CapacityTotal{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Total Capacity"
    },
    {
     "expr": "Cluster_CapacityUsed{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Used Capacity"
    }
   ]
  },
  { "title": "Logical Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Directories Created",
   "type": "stat",
   "description": "Displays the current number of how many directories GooseFS has created since starting",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Master_DirectoriesCreated{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Directories Created"
    }
   ]
  },
  {
   "title": "File Infos Got",
   "type": "stat",
   "description": "displays the number of times the FileInfosGot operation was called",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Master_FileInfosGot{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} FileInfo Got"
    }
   ]
  },
  {
   "title": "Total Paths",
   "type": "stat",
   "description": "Displays the total paths located in the GooseFS file system",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Master_TotalPaths{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Total Paths"
    }
   ]
  },
  {
   "title": "Complete File Operations",
   "type": "stat",
   "description": "Displays how many times the CompleteFile operation has been called",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Master_CompleteFileOps{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Complete FIle Ops"
    }
   ]
  },
  {
   "title": "Create Directory Oprtations",
   "type": "stat",
   "description": "Displays the amount of directories that GooseFS has created (Not the current amount of directories)",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Master_CreateDirectoryOps{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Directory Ops"
    }
   ]
  },
  {
   "title": "Delete Path Operations",
   "type": "stat",
   "description": "Displays how many times the deletePath operation has been called (And how many total paths have been deleted)",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Master_DeletePathOps{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} DeletePath Ops"
    }
   ]
  },
  {
   "title": "Files Pinned",
   "type": "stat",
   "description": "Displays the current number of pinned files in GooseFS",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Master_FilesPinned{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Files Pinned"
    }
   ]
  },
  {
   "title": "Mount Operations",
   "type": "stat",
   "description": "Displays how many times the mount operation has been called (including failed invocations)",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Master_MountOps{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Mount"
    }
   ]
  },
  {
   "title": "Files Freed",
   "type": "stat",
   "description": "Displays the current number of freed files in GooseFS",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Master_FilesFreed{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Files Freed"
    }
   ]
  },
  {
   "title": "Unmount Operations",
   "type": "stat",
   "description": "Displays how many times the unmount operation has been called",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Master_UnmountOps{fluid_runtime=~\"$fluid_runtime\",namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Unmount Ops"
    }
   ]
  },
  { "title": "GooseFS Metadata Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "GetStatus Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_GetStatus_User:$goosefs_user\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.5\"}",
     "legendFormat": "{{fluid_runtime}} GetStatus  Total quantile=0.5"
    },
    {
     "expr": "{__name__=\"Master_GetStatus_User:$goosefs_user\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.95\"}",
     "legendFormat": "{{fluid_runtime}} GetStatus  Total quantile=0.95"
    },
    {
     "expr": "{__name__=\"Master_GetStatus_User:$goosefs_user\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.99\"}",
     "legendFormat": "{{fluid_runtime}} GetStatus  Total quantile=0.99"
    }
   ]
  },
  {
   "title": "ListStatus Operation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_ListStatus_User:$goosefs_user\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.5\"}",
     "legendFormat": "{{fluid_runtime}} ListStatus quantile=0.5"
    },
    {
     "expr": "{__name__=\"Master_ListStatus_User:$goosefs_user\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.95\"}",
     "legendFormat": "{{fluid_runtime}} ListStatus quantile=0.95"
    },
    {
     "expr": "{__name__=\"Master_ListStatus_User:$goosefs_user\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.99\"}",
     "legendFormat": "{{fluid_runtime}} ListStatus quantile=0.99"
    }
   ]
  },
  {
   "title": "Get Configuration Operation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_getConfiguration\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.5\"}",
     "legendFormat": "{{fluid_runtime}} GetConfiguration quantile=0.5"
    },
    {
     "expr": "{__name__=\"Master_getConfiguration\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.95\"}",
     "legendFormat": "{{fluid_runtime}} GetConfiguration quantile=0.95"
    },
    {
     "expr": "{__name__=\"Master_getConfiguration\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\",quantile=\"0.99\"}",
     "legendFormat": "{{fluid_runtime}} GetConfiguration quantile=0.99"
    }
   ]
  },
  {
   "title": "Block Heartbeat Operation",
   "type": "graph",
   "description": "Displays the 50th, 95th, and 99th percentiles call time for the blockHeartbeat metadata operation.\n\nNote: This is not a graph for the actual Block Heartbeat just how long it took the operation to run",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"Master_blockHeartbeat_User:$goosefs_user\",fluid_runtime=~\"$fluid_runtime\",quantile=\"0.5\"}",
     "legendFormat": "{{fluid_runtime}} BlockHeartBeat quantile=0.5"
    },
    {
     "expr": "{__name__=\"Master_blockHeartbeat_User:$goosefs_user\",fluid_runtime=~\"$fluid_runtime\",quantile=\"0.95\"}",
     "legendFormat": "{{fluid_runtime}} BlockHeartBeat quantile=0.95"
    },
    {
     "expr": "{__name__=\"Master_blockHeartbeat_User:$goosefs_user\",fluid_runtime=~\"$fluid_runtime\",quantile=\"0.99\"}",
     "legendFormat": "{{fluid_runtime}} BlockHeartBeat quantile=0.99"
    }
   ]
  },
  { "title": "Master JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Master Memory Pools",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"pools_Compressed_Class_Space_used\", fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Master Memory Pools Compressed Class Space Used"
    },
    {
     "expr": "{__name__=\"pools_Metaspace_used\", fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Master Memory Pools Metdspace Used"
    },
    {
     "expr": "{__name__=\"pools_PS_Eden_Space_used\", fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "{__name__=\"pools_PS_Survivor_Space_used\", fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Master Heap Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"heap_used\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Master Heap Used"
    },
    {
     "expr": "{__name__=\"heap_max\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Master Heap Max"
    },
    {
     "expr": "{__name__=\"non_heap_used\",fluid_runtime=~\"$fluid_runtime\", namespace=~\"$namespace\"}",
     "legendFormat": "{{fluid_runtime}} Master Non Heap Used"
    }
   ]
  },
  {
   "title": "Master Total Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"total_max\",fluid_runtime=~\"$fluid_runtime\"}",
     "legendFormat": "{{fluid_runtime}} Master Total Max Memory"
    },
    {
     "expr": "{__name__=\"total_used\",fluid_runtime=~\"$fluid_runtime\"}",
     "legendFormat": "{{fluid_runtime}} Master Total Used Memory"
    }
   ]
  }
 ]
}