/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	scheme "github.com/fluid-cloudnative/fluid/pkg/apis/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DataLoadsGetter has a method to return a DataLoadInterface.
// A group's client should implement this interface.
type DataLoadsGetter interface {
	DataLoads(namespace string) DataLoadInterface
}

// DataLoadInterface has methods to work with DataLoad resources.
type DataLoadInterface interface {
	Create(ctx context.Context, dataLoad *v1alpha1.DataLoad, opts v1.CreateOptions) (*v1alpha1.DataLoad, error)
	Update(ctx context.Context, dataLoad *v1alpha1.DataLoad, opts v1.UpdateOptions) (*v1alpha1.DataLoad, error)
	UpdateStatus(ctx context.Context, dataLoad *v1alpha1.DataLoad, opts v1.UpdateOptions) (*v1alpha1.DataLoad, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DataLoad, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DataLoadList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DataLoad, err error)
	DataLoadExpansion
}

// dataLoads implements DataLoadInterface
type dataLoads struct {
	client rest.Interface
	ns     string
}

// newDataLoads returns a DataLoads
func newDataLoads(c *DataV1alpha1Client, namespace string) *dataLoads {
	return &dataLoads{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dataLoad, and returns the corresponding dataLoad object, and an error if there is any.
func (c *dataLoads) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DataLoad, err error) {
	result = &v1alpha1.DataLoad{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dataloads").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DataLoads that match those selectors.
func (c *dataLoads) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DataLoadList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DataLoadList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dataloads").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dataLoads.
func (c *dataLoads) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dataloads").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dataLoad and creates it.  Returns the server's representation of the dataLoad, and an error, if there is any.
func (c *dataLoads) Create(ctx context.Context, dataLoad *v1alpha1.DataLoad, opts v1.CreateOptions) (result *v1alpha1.DataLoad, err error) {
	result = &v1alpha1.DataLoad{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dataloads").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dataLoad).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dataLoad and updates it. Returns the server's representation of the dataLoad, and an error, if there is any.
func (c *dataLoads) Update(ctx context.Context, dataLoad *v1alpha1.DataLoad, opts v1.UpdateOptions) (result *v1alpha1.DataLoad, err error) {
	result = &v1alpha1.DataLoad{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dataloads").
		Name(dataLoad.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dataLoad).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *dataLoads) UpdateStatus(ctx context.Context, dataLoad *v1alpha1.DataLoad, opts v1.UpdateOptions) (result *v1alpha1.DataLoad, err error) {
	result = &v1alpha1.DataLoad{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dataloads").
		Name(dataLoad.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dataLoad).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dataLoad and deletes it. Returns an error if one occurs.
func (c *dataLoads) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dataloads").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dataLoads) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dataloads").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dataLoad.
func (c *dataLoads) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DataLoad, err error) {
	result = &v1alpha1.DataLoad{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dataloads").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
