/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	scheme "github.com/fluid-cloudnative/fluid/pkg/apis/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GooseFSRuntimesGetter has a method to return a GooseFSRuntimeInterface.
// A group's client should implement this interface.
type GooseFSRuntimesGetter interface {
	GooseFSRuntimes(namespace string) GooseFSRuntimeInterface
}

// GooseFSRuntimeInterface has methods to work with GooseFSRuntime resources.
type GooseFSRuntimeInterface interface {
	Create(ctx context.Context, gooseFSRuntime *v1alpha1.GooseFSRuntime, opts v1.CreateOptions) (*v1alpha1.GooseFSRuntime, error)
	Update(ctx context.Context, gooseFSRuntime *v1alpha1.GooseFSRuntime, opts v1.UpdateOptions) (*v1alpha1.GooseFSRuntime, error)
	UpdateStatus(ctx context.Context, gooseFSRuntime *v1alpha1.GooseFSRuntime, opts v1.UpdateOptions) (*v1alpha1.GooseFSRuntime, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GooseFSRuntime, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GooseFSRuntimeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GooseFSRuntime, err error)
	GooseFSRuntimeExpansion
}

// gooseFSRuntimes implements GooseFSRuntimeInterface
type gooseFSRuntimes struct {
	client rest.Interface
	ns     string
}

// newGooseFSRuntimes returns a GooseFSRuntimes
func newGooseFSRuntimes(c *DataV1alpha1Client, namespace string) *gooseFSRuntimes {
	return &gooseFSRuntimes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gooseFSRuntime, and returns the corresponding gooseFSRuntime object, and an error if there is any.
func (c *gooseFSRuntimes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GooseFSRuntime, err error) {
	result = &v1alpha1.GooseFSRuntime{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("goosefsruntimes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GooseFSRuntimes that match those selectors.
func (c *gooseFSRuntimes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GooseFSRuntimeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GooseFSRuntimeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("goosefsruntimes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gooseFSRuntimes.
func (c *gooseFSRuntimes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("goosefsruntimes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a gooseFSRuntime and creates it.  Returns the server's representation of the gooseFSRuntime, and an error, if there is any.
func (c *gooseFSRuntimes) Create(ctx context.Context, gooseFSRuntime *v1alpha1.GooseFSRuntime, opts v1.CreateOptions) (result *v1alpha1.GooseFSRuntime, err error) {
	result = &v1alpha1.GooseFSRuntime{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("goosefsruntimes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gooseFSRuntime).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a gooseFSRuntime and updates it. Returns the server's representation of the gooseFSRuntime, and an error, if there is any.
func (c *gooseFSRuntimes) Update(ctx context.Context, gooseFSRuntime *v1alpha1.GooseFSRuntime, opts v1.UpdateOptions) (result *v1alpha1.GooseFSRuntime, err error) {
	result = &v1alpha1.GooseFSRuntime{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("goosefsruntimes").
		Name(gooseFSRuntime.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gooseFSRuntime).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *gooseFSRuntimes) UpdateStatus(ctx context.Context, gooseFSRuntime *v1alpha1.GooseFSRuntime, opts v1.UpdateOptions) (result *v1alpha1.GooseFSRuntime, err error) {
	result = &v1alpha1.GooseFSRuntime{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("goosefsruntimes").
		Name(gooseFSRuntime.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gooseFSRuntime).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the gooseFSRuntime and deletes it. Returns an error if one occurs.
func (c *gooseFSRuntimes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("goosefsruntimes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gooseFSRuntimes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("goosefsruntimes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched gooseFSRuntime.
func (c *gooseFSRuntimes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GooseFSRuntime, err error) {
	result = &v1alpha1.GooseFSRuntime{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("goosefsruntimes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
