/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	scheme "github.com/fluid-cloudnative/fluid/pkg/apis/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// JindoRuntimesGetter has a method to return a JindoRuntimeInterface.
// A group's client should implement this interface.
type JindoRuntimesGetter interface {
	JindoRuntimes(namespace string) JindoRuntimeInterface
}

// JindoRuntimeInterface has methods to work with JindoRuntime resources.
type JindoRuntimeInterface interface {
	Create(ctx context.Context, jindoRuntime *v1alpha1.JindoRuntime, opts v1.CreateOptions) (*v1alpha1.JindoRuntime, error)
	Update(ctx context.Context, jindoRuntime *v1alpha1.JindoRuntime, opts v1.UpdateOptions) (*v1alpha1.JindoRuntime, error)
	UpdateStatus(ctx context.Context, jindoRuntime *v1alpha1.JindoRuntime, opts v1.UpdateOptions) (*v1alpha1.JindoRuntime, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.JindoRuntime, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.JindoRuntimeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.JindoRuntime, err error)
	JindoRuntimeExpansion
}

// jindoRuntimes implements JindoRuntimeInterface
type jindoRuntimes struct {
	client rest.Interface
	ns     string
}

// newJindoRuntimes returns a JindoRuntimes
func newJindoRuntimes(c *DataV1alpha1Client, namespace string) *jindoRuntimes {
	return &jindoRuntimes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the jindoRuntime, and returns the corresponding jindoRuntime object, and an error if there is any.
func (c *jindoRuntimes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.JindoRuntime, err error) {
	result = &v1alpha1.JindoRuntime{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jindoruntimes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of JindoRuntimes that match those selectors.
func (c *jindoRuntimes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.JindoRuntimeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.JindoRuntimeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jindoruntimes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested jindoRuntimes.
func (c *jindoRuntimes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("jindoruntimes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a jindoRuntime and creates it.  Returns the server's representation of the jindoRuntime, and an error, if there is any.
func (c *jindoRuntimes) Create(ctx context.Context, jindoRuntime *v1alpha1.JindoRuntime, opts v1.CreateOptions) (result *v1alpha1.JindoRuntime, err error) {
	result = &v1alpha1.JindoRuntime{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("jindoruntimes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jindoRuntime).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a jindoRuntime and updates it. Returns the server's representation of the jindoRuntime, and an error, if there is any.
func (c *jindoRuntimes) Update(ctx context.Context, jindoRuntime *v1alpha1.JindoRuntime, opts v1.UpdateOptions) (result *v1alpha1.JindoRuntime, err error) {
	result = &v1alpha1.JindoRuntime{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jindoruntimes").
		Name(jindoRuntime.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jindoRuntime).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *jindoRuntimes) UpdateStatus(ctx context.Context, jindoRuntime *v1alpha1.JindoRuntime, opts v1.UpdateOptions) (result *v1alpha1.JindoRuntime, err error) {
	result = &v1alpha1.JindoRuntime{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jindoruntimes").
		Name(jindoRuntime.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(jindoRuntime).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the jindoRuntime and deletes it. Returns an error if one occurs.
func (c *jindoRuntimes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jindoruntimes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *jindoRuntimes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jindoruntimes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched jindoRuntime.
func (c *jindoRuntimes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.JindoRuntime, err error) {
	result = &v1alpha1.JindoRuntime{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("jindoruntimes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
