/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
	scheme "github.com/fluid-cloudnative/fluid/pkg/apis/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// JuiceFSRuntimesGetter has a method to return a JuiceFSRuntimeInterface.
// A group's client should implement this interface.
type JuiceFSRuntimesGetter interface {
	JuiceFSRuntimes(namespace string) JuiceFSRuntimeInterface
}

// JuiceFSRuntimeInterface has methods to work with JuiceFSRuntime resources.
type JuiceFSRuntimeInterface interface {
	Create(ctx context.Context, juiceFSRuntime *v1alpha1.JuiceFSRuntime, opts v1.CreateOptions) (*v1alpha1.JuiceFSRuntime, error)
	Update(ctx context.Context, juiceFSRuntime *v1alpha1.JuiceFSRuntime, opts v1.UpdateOptions) (*v1alpha1.JuiceFSRuntime, error)
	UpdateStatus(ctx context.Context, juiceFSRuntime *v1alpha1.JuiceFSRuntime, opts v1.UpdateOptions) (*v1alpha1.JuiceFSRuntime, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.JuiceFSRuntime, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.JuiceFSRuntimeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.JuiceFSRuntime, err error)
	JuiceFSRuntimeExpansion
}

// juiceFSRuntimes implements JuiceFSRuntimeInterface
type juiceFSRuntimes struct {
	client rest.Interface
	ns     string
}

// newJuiceFSRuntimes returns a JuiceFSRuntimes
func newJuiceFSRuntimes(c *DataV1alpha1Client, namespace string) *juiceFSRuntimes {
	return &juiceFSRuntimes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the juiceFSRuntime, and returns the corresponding juiceFSRuntime object, and an error if there is any.
func (c *juiceFSRuntimes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.JuiceFSRuntime, err error) {
	result = &v1alpha1.JuiceFSRuntime{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("juicefsruntimes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of JuiceFSRuntimes that match those selectors.
func (c *juiceFSRuntimes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.JuiceFSRuntimeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.JuiceFSRuntimeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("juicefsruntimes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested juiceFSRuntimes.
func (c *juiceFSRuntimes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("juicefsruntimes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a juiceFSRuntime and creates it.  Returns the server's representation of the juiceFSRuntime, and an error, if there is any.
func (c *juiceFSRuntimes) Create(ctx context.Context, juiceFSRuntime *v1alpha1.JuiceFSRuntime, opts v1.CreateOptions) (result *v1alpha1.JuiceFSRuntime, err error) {
	result = &v1alpha1.JuiceFSRuntime{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("juicefsruntimes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(juiceFSRuntime).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a juiceFSRuntime and updates it. Returns the server's representation of the juiceFSRuntime, and an error, if there is any.
func (c *juiceFSRuntimes) Update(ctx context.Context, juiceFSRuntime *v1alpha1.JuiceFSRuntime, opts v1.UpdateOptions) (result *v1alpha1.JuiceFSRuntime, err error) {
	result = &v1alpha1.JuiceFSRuntime{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("juicefsruntimes").
		Name(juiceFSRuntime.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(juiceFSRuntime).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *juiceFSRuntimes) UpdateStatus(ctx context.Context, juiceFSRuntime *v1alpha1.JuiceFSRuntime, opts v1.UpdateOptions) (result *v1alpha1.JuiceFSRuntime, err error) {
	result = &v1alpha1.JuiceFSRuntime{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("juicefsruntimes").
		Name(juiceFSRuntime.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(juiceFSRuntime).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the juiceFSRuntime and deletes it. Returns an error if one occurs.
func (c *juiceFSRuntimes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("juicefsruntimes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *juiceFSRuntimes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("juicefsruntimes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched juiceFSRuntime.
func (c *juiceFSRuntimes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.JuiceFSRuntime, err error) {
	result = &v1alpha1.JuiceFSRuntime{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("juicefsruntimes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
