/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AlluxioRuntimeListerExpansion allows custom methods to be added to
// AlluxioRuntimeLister.
type AlluxioRuntimeListerExpansion interface{}

// AlluxioRuntimeNamespaceListerExpansion allows custom methods to be added to
// AlluxioRuntimeNamespaceLister.
type AlluxioRuntimeNamespaceListerExpansion interface{}

// DataBackupListerExpansion allows custom methods to be added to
// DataBackupLister.
type DataBackupListerExpansion interface{}

// DataBackupNamespaceListerExpansion allows custom methods to be added to
// DataBackupNamespaceLister.
type DataBackupNamespaceListerExpansion interface{}

// DataLoadListerExpansion allows custom methods to be added to
// DataLoadLister.
type DataLoadListerExpansion interface{}

// DataLoadNamespaceListerExpansion allows custom methods to be added to
// DataLoadNamespaceLister.
type DataLoadNamespaceListerExpansion interface{}

// DataMigrateListerExpansion allows custom methods to be added to
// DataMigrateLister.
type DataMigrateListerExpansion interface{}

// DataMigrateNamespaceListerExpansion allows custom methods to be added to
// DataMigrateNamespaceLister.
type DataMigrateNamespaceListerExpansion interface{}

// DatasetListerExpansion allows custom methods to be added to
// DatasetLister.
type DatasetListerExpansion interface{}

// DatasetNamespaceListerExpansion allows custom methods to be added to
// DatasetNamespaceLister.
type DatasetNamespaceListerExpansion interface{}

// EFCRuntimeListerExpansion allows custom methods to be added to
// EFCRuntimeLister.
type EFCRuntimeListerExpansion interface{}

// EFCRuntimeNamespaceListerExpansion allows custom methods to be added to
// EFCRuntimeNamespaceLister.
type EFCRuntimeNamespaceListerExpansion interface{}

// GooseFSRuntimeListerExpansion allows custom methods to be added to
// GooseFSRuntimeLister.
type GooseFSRuntimeListerExpansion interface{}

// GooseFSRuntimeNamespaceListerExpansion allows custom methods to be added to
// GooseFSRuntimeNamespaceLister.
type GooseFSRuntimeNamespaceListerExpansion interface{}

// JindoRuntimeListerExpansion allows custom methods to be added to
// JindoRuntimeLister.
type JindoRuntimeListerExpansion interface{}

// JindoRuntimeNamespaceListerExpansion allows custom methods to be added to
// JindoRuntimeNamespaceLister.
type JindoRuntimeNamespaceListerExpansion interface{}

// JuiceFSRuntimeListerExpansion allows custom methods to be added to
// JuiceFSRuntimeLister.
type JuiceFSRuntimeListerExpansion interface{}

// JuiceFSRuntimeNamespaceListerExpansion allows custom methods to be added to
// JuiceFSRuntimeNamespaceLister.
type JuiceFSRuntimeNamespaceListerExpansion interface{}
